"""CnCast: vertical Cn^2 profile prediction with published baselines and intervals.

Baselines first (``cncast.baselines``): the Hufnagel-Valley family including the
HV 5/7 parameterisation, and the SLC-Day / SLC-Night piecewise profiles, each
with its stated altitude validity range.  All of them are *climatological*
models, not forecasts.

Derived quantities (``cncast.seeing``): Fried parameter r0, isoplanatic angle
theta0, Greenwood frequency f_G, long-exposure seeing.

Learned model (``cncast.model``): quantile gradient boosting from surface
meteorology + altitude to log10 Cn^2, with a prediction interval.  It is trained
on SYNTHETIC data generated by ``cncast.dataset`` - see ``DATASET_CARD.md``.

Research-grade software.  Not flight-qualified, not certified, and not approved
for operational aerospace use.  The learned model is not certified for
operational flight use.
"""

from .baselines import (
    HV57_A0,
    HV57_RMS_WIND,
    HV_VALID_RANGE_M,
    SLC_DAY_VALID_RANGE_M,
    SLC_NIGHT_VALID_RANGE_M,
    bufton_wind,
    hufnagel_valley,
    hv57,
    rms_high_altitude_wind,
    slc_day,
    slc_night,
)
from .dataset import (
    ALTITUDE_MAX_M,
    ALTITUDE_MIN_M,
    FEATURE_NAMES,
    Scenario,
    build_table,
    default_altitude_grid,
    generate_scenarios,
    met_features,
    profile_cn2,
    scenario_features,
    split_scenarios,
)
from .model import (
    TRAINING_DOMAIN,
    ClimatologyBaseline,
    CnCastModel,
    Hv57Baseline,
    ProfilePrediction,
    SlcBaseline,
    interval_coverage,
    train_default_model,
)
from .seeing import (
    fried_parameter,
    greenwood_frequency,
    isoplanatic_angle,
    seeing_fwhm_arcsec,
    turbulence_moment,
)

__version__ = "0.1.0"

__all__ = [
    "ALTITUDE_MAX_M",
    "ALTITUDE_MIN_M",
    "FEATURE_NAMES",
    "HV57_A0",
    "HV57_RMS_WIND",
    "HV_VALID_RANGE_M",
    "SLC_DAY_VALID_RANGE_M",
    "SLC_NIGHT_VALID_RANGE_M",
    "TRAINING_DOMAIN",
    "ClimatologyBaseline",
    "CnCastModel",
    "Hv57Baseline",
    "ProfilePrediction",
    "Scenario",
    "SlcBaseline",
    "__version__",
    "bufton_wind",
    "build_table",
    "default_altitude_grid",
    "fried_parameter",
    "generate_scenarios",
    "greenwood_frequency",
    "hufnagel_valley",
    "hv57",
    "interval_coverage",
    "isoplanatic_angle",
    "met_features",
    "profile_cn2",
    "rms_high_altitude_wind",
    "scenario_features",
    "seeing_fwhm_arcsec",
    "slc_day",
    "slc_night",
    "split_scenarios",
    "train_default_model",
    "turbulence_moment",
]
