"""Kolmogorov phase screens and their exact spectral gradients.

Statistical model
-----------------
Kolmogorov turbulence in the near field gives the wavefront phase the power
spectral density

    Phi_phi(f) = 0.0229 * r0**(-5/3) * f**(-11/3)      [rad^2 m^2]

with ``f`` the **cyclic** spatial frequency [cycles/m] and ``r0`` the Fried
coherence length [m]. Source: F. Roddier, "The effects of atmospheric
turbulence in optical astronomy", *Progress in Optics* **XIX**, 281-376 (1981),
Sec. 3; the same expression appears as Eq. 3.31 of J. W. Hardy, *Adaptive
Optics for Astronomical Telescopes*, Oxford University Press 1998. Assumptions:
Kolmogorov inertial-range statistics with an infinite outer scale and a zero
inner scale, near-field (no scintillation), a single thin layer, frozen flow
not required because only single realisations are used.

The equivalent second-order description is the phase structure function

    D_phi(r) = <|phi(x + r) - phi(x)|^2> = 6.88 (r / r0)**(5/3)     [rad^2]

whose coefficient is exactly ``2 * (24/5 * Gamma(6/5))**(5/6) = 6.883877...``
(D. L. Fried, "Statistics of a geometric representation of wavefront
distortion", *JOSA* **55** (11), 1427-1435, 1965, where ``r0`` is defined;
Roddier 1981 Sec. 2). Validity range: ``l0 << r << L0``, i.e. within the
inertial subrange.

Numerical generation
--------------------
Screens are generated by the standard Fourier method: draw a circular complex
Gaussian spectrum with variance ``Phi_phi(f) df**2``, zero the ``f = 0`` bin
(infinite power, and piston is unobservable from slopes anyway), and take the
real part of the inverse transform. Gradients are obtained **exactly** for the
band-limited screen by multiplying the spectrum by ``2 pi i f_x`` before
transforming, so no finite differencing is used anywhere in the data
generation.

**Known deficiency, and the mitigation.** A periodic FFT grid of side ``L``
contains no power below ``1/L``, so plain FFT screens systematically
under-produce the low-order aberrations that dominate Kolmogorov turbulence
(tip/tilt above all) and their structure function falls short of
``6.88 (r/r0)**(5/3)`` at large separations. The standard fix, implemented
here, adds explicit subharmonic components on grids of spacing ``df/3**p``:
R. G. Lane, A. Glindemann and J. C. Dainty, "Simulation of a Kolmogorov phase
screen", *Waves in Random Media* **2** (3), 209-224 (1992). The residual error
after three subharmonic levels is measured in `validation/VALIDATION.md` rather
than assumed.

Units
-----
Phase is in radians. Grid spacing ``dx`` and ``r0`` are in metres. Gradients
are in radians per metre.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from math import gamma

import numpy as np
from numpy.typing import NDArray

__all__ = [
    "KOLMOGOROV_PSD_COEFF",
    "STRUCTURE_FUNCTION_COEFF",
    "kolmogorov_psd",
    "structure_function_theory",
    "KolmogorovScreens",
    "measure_structure_function",
]

#: Midpoint-quadrature order used per spectral cell when integrating the PSD. [-]
_CELL_QUAD: int = 7

#: Coefficient of the Kolmogorov phase PSD in cyclic frequency (Roddier 1981;
#: Hardy 1998 Eq. 3.31). Dimensionless.
KOLMOGOROV_PSD_COEFF: float = 0.0229

#: Coefficient of the Kolmogorov phase structure function,
#: ``2 * (24/5 * Gamma(6/5))**(5/6)`` (Fried 1965; Roddier 1981). Dimensionless.
STRUCTURE_FUNCTION_COEFF: float = 2.0 * (24.0 / 5.0 * gamma(6.0 / 5.0)) ** (5.0 / 6.0)


def kolmogorov_psd(f: NDArray[np.float64], r0: float) -> NDArray[np.float64]:
    """Kolmogorov phase PSD ``0.0229 r0^(-5/3) f^(-11/3)`` [rad^2 m^2].

    Parameters
    ----------
    f : ndarray
        Cyclic spatial frequency modulus [cycles/m]. Zeros return ``inf``.
    r0 : float
        Fried parameter [m], > 0.

    Notes
    -----
    Infinite outer scale, zero inner scale. For a finite outer scale use the
    von Karman form instead; that is not implemented here (see README
    Limitations).
    """
    r0f = float(r0)
    if not np.isfinite(r0f) or r0f <= 0.0:
        raise ValueError(f"r0 must be finite and > 0 m, got {r0!r}")
    fa = np.asarray(f, dtype=float)
    if np.any(fa < 0.0):
        raise ValueError("f must be a non-negative frequency modulus")
    with np.errstate(divide="ignore"):
        return KOLMOGOROV_PSD_COEFF * r0f ** (-5.0 / 3.0) * fa ** (-11.0 / 3.0)


def structure_function_theory(r: NDArray[np.float64], r0: float) -> NDArray[np.float64]:
    """Kolmogorov phase structure function ``6.883877 (r/r0)^(5/3)`` [rad^2].

    Parameters
    ----------
    r : ndarray
        Separation [m], >= 0.
    r0 : float
        Fried parameter [m], > 0.

    Validity: inertial subrange only (inner scale << r << outer scale).
    """
    r0f = float(r0)
    if not np.isfinite(r0f) or r0f <= 0.0:
        raise ValueError(f"r0 must be finite and > 0 m, got {r0!r}")
    ra = np.asarray(r, dtype=float)
    if np.any(ra < 0.0):
        raise ValueError("r must be non-negative")
    return STRUCTURE_FUNCTION_COEFF * (ra / r0f) ** (5.0 / 3.0)


@dataclass
class KolmogorovScreens:
    """Batch generator of Kolmogorov phase screens with exact spectral gradients.

    Parameters
    ----------
    n_grid : int
        Grid points per side [-], >= 8. Powers of two are fastest.
    dx : float
        Grid spacing [m], > 0. The screen period is ``n_grid * dx``.
    r0 : float
        Fried parameter [m], > 0, defined at the wavelength the phase refers to.
    n_subharmonics : int
        Number of Lane et al. (1992) subharmonic levels [-], >= 0. Each level
        adds the eight non-zero cells of a 3x3 grid at spacing ``df / 3**p``.
    seed : int
        Seed for ``numpy.random.default_rng``; generation is deterministic and
        bit-reproducible for a given seed and call sequence.

    Notes
    -----
    All returned arrays are ``(n_screens, n_grid, n_grid)``, indexed
    ``[screen, iy, ix]``. Phase is in radians, gradients in radians per metre.
    Each screen has its spatial mean removed (piston is unobservable).
    """

    n_grid: int
    dx: float
    r0: float
    n_subharmonics: int = 3
    seed: int = 0
    _rng: np.random.Generator = field(init=False, repr=False)

    def __post_init__(self) -> None:
        if isinstance(self.n_grid, bool) or not isinstance(self.n_grid, (int, np.integer)):
            raise TypeError(f"n_grid must be an integer, got {self.n_grid!r}")
        if self.n_grid < 8:
            raise ValueError(f"n_grid must be >= 8, got {self.n_grid}")
        if not np.isfinite(float(self.dx)) or float(self.dx) <= 0.0:
            raise ValueError(f"dx must be finite and > 0 m, got {self.dx!r}")
        if not np.isfinite(float(self.r0)) or float(self.r0) <= 0.0:
            raise ValueError(f"r0 must be finite and > 0 m, got {self.r0!r}")
        if isinstance(self.n_subharmonics, bool) or self.n_subharmonics < 0:
            raise ValueError(f"n_subharmonics must be >= 0, got {self.n_subharmonics!r}")
        self.n_grid = int(self.n_grid)
        self.dx = float(self.dx)
        self.r0 = float(self.r0)
        self.n_subharmonics = int(self.n_subharmonics)
        self._rng = np.random.default_rng(self.seed)
        self._setup()

    def _cell_sigma(
        self, fx_centre: NDArray[np.float64], fy_centre: NDArray[np.float64], df: float
    ) -> NDArray[np.float64]:
        """RMS amplitude of one spectral cell: ``sqrt(integral of PSD over the cell)``.

        Evaluating ``sqrt(PSD(f_centre)) * df`` instead is the textbook
        shortcut, but ``f**(-11/3)`` varies by orders of magnitude across the
        low-frequency cells and the shortcut loses a large fraction of the
        low-order power. A ``_CELL_QUAD**2`` midpoint quadrature inside each
        cell is used instead. Cells that contain ``f = 0`` are returned as 0
        and are filled in by the subharmonic levels.
        """
        q = _CELL_QUAD
        offs = ((np.arange(q) + 0.5) / q - 0.5) * df
        ox, oy = np.meshgrid(offs, offs, indexing="xy")
        fxs = fx_centre[..., None, None] + ox
        fys = fy_centre[..., None, None] + oy
        fm = np.hypot(fxs, fys)
        good = fm > 0.0
        psd = np.zeros_like(fm)
        psd[good] = kolmogorov_psd(fm[good], self.r0)
        var = np.mean(psd, axis=(-2, -1)) * df * df
        var[~np.all(good, axis=(-2, -1))] = 0.0
        return np.sqrt(var)

    def _setup(self) -> None:
        n = self.n_grid
        self._df = 1.0 / (n * self.dx)
        fx = np.fft.fftfreq(n, d=self.dx)
        fxx, fyy = np.meshgrid(fx, fx, indexing="xy")
        amp = self._cell_sigma(fxx, fyy, self._df)
        amp[0, 0] = 0.0
        self._amp = amp
        self._fxx = fxx
        self._fyy = fyy

        # Subharmonic basis, evaluated once on the grid.
        coords = (np.arange(n) - n // 2) * self.dx
        gx, gy = np.meshgrid(coords, coords, indexing="xy")
        basis: list[NDArray[np.complex128]] = []
        bxs: list[NDArray[np.complex128]] = []
        bys: list[NDArray[np.complex128]] = []
        amps: list[float] = []
        for p in range(1, self.n_subharmonics + 1):
            dfp = self._df / (3.0**p)
            for iy in (-1, 0, 1):
                for ix in (-1, 0, 1):
                    if ix == 0 and iy == 0:
                        continue
                    fxs, fys = ix * dfp, iy * dfp
                    a = float(
                        self._cell_sigma(np.array([fxs]), np.array([fys]), dfp)[0]
                    )
                    ph = np.exp(2j * np.pi * (fxs * gx + fys * gy))
                    basis.append(ph)
                    bxs.append(2j * np.pi * fxs * ph)
                    bys.append(2j * np.pi * fys * ph)
                    amps.append(a)
        self._n_sh = len(basis)
        if self._n_sh:
            self._sh = np.array(basis).reshape(self._n_sh, -1)
            self._shx = np.array(bxs).reshape(self._n_sh, -1)
            self._shy = np.array(bys).reshape(self._n_sh, -1)
            self._sh_amp = np.array(amps)

    def generate(
        self, n_screens: int
    ) -> tuple[NDArray[np.float64], NDArray[np.float64], NDArray[np.float64]]:
        """Generate ``n_screens`` screens and their gradients.

        Returns
        -------
        phase : ndarray, shape (n_screens, n_grid, n_grid)
            Phase [rad], spatial mean removed.
        dphidx, dphidy : ndarray, same shape
            Exact gradients of the band-limited screen [rad/m].
        """
        if isinstance(n_screens, bool) or not isinstance(n_screens, (int, np.integer)):
            raise TypeError(f"n_screens must be an integer, got {n_screens!r}")
        if n_screens < 1:
            raise ValueError(f"n_screens must be >= 1, got {n_screens}")
        n = self.n_grid
        shape = (int(n_screens), n, n)
        noise = self._rng.standard_normal(shape) + 1j * self._rng.standard_normal(shape)
        spec = noise * self._amp
        scale = n * n
        phase = np.real(np.fft.ifft2(spec, axes=(-2, -1))) * scale
        gx = np.real(np.fft.ifft2(spec * (2j * np.pi * self._fxx), axes=(-2, -1))) * scale
        gy = np.real(np.fft.ifft2(spec * (2j * np.pi * self._fyy), axes=(-2, -1))) * scale

        if self._n_sh:
            c = (
                self._rng.standard_normal((int(n_screens), self._n_sh))
                + 1j * self._rng.standard_normal((int(n_screens), self._n_sh))
            ) * self._sh_amp
            phase += np.real(c @ self._sh).reshape(shape)
            gx += np.real(c @ self._shx).reshape(shape)
            gy += np.real(c @ self._shy).reshape(shape)

        phase -= phase.mean(axis=(-2, -1), keepdims=True)
        return phase, gx, gy


def measure_structure_function(
    phase: NDArray[np.float64], dx: float, max_lag: int | None = None
) -> tuple[NDArray[np.float64], NDArray[np.float64]]:
    """Empirical phase structure function along the grid rows.

    Parameters
    ----------
    phase : ndarray, shape (n_screens, ny, nx) or (ny, nx)
        Phase screens [rad].
    dx : float
        Grid spacing [m], > 0.
    max_lag : int, optional
        Largest lag in samples. Defaults to ``nx // 4`` -- beyond about a
        quarter of the period the FFT screen's own periodicity dominates.

    Returns
    -------
    r : ndarray
        Separations [m], starting at ``dx``.
    d : ndarray
        ``<|phi(x + r) - phi(x)|^2>`` [rad^2], averaged over all rows, screens
        and starting positions.
    """
    arr = np.asarray(phase, dtype=float)
    if arr.ndim == 2:
        arr = arr[None, ...]
    if arr.ndim != 3:
        raise ValueError(f"phase must be 2-D or 3-D, got shape {arr.shape}")
    d0 = float(dx)
    if not np.isfinite(d0) or d0 <= 0.0:
        raise ValueError(f"dx must be finite and > 0 m, got {dx!r}")
    nx = arr.shape[-1]
    lag_max = nx // 4 if max_lag is None else int(max_lag)
    if lag_max < 1 or lag_max >= nx:
        raise ValueError(f"max_lag must be in 1..{nx - 1}, got {lag_max}")
    lags = np.arange(1, lag_max + 1)
    d = np.array([np.mean((arr[..., k:] - arr[..., :-k]) ** 2) for k in lags])
    return lags * d0, d
