"""Synthetic per-stage latency traces, generated by seed.

What is modelled
----------------
Four stage durations per iteration (``sense``, ``estimate``, ``control``,
``actuate``), driven by a two-state Markov chain over "calm" and "burst"
regimes:

* The regime sequence ``z[k]`` is a two-state discrete Markov chain with
  transition matrix ``P``. Markov-modulated models of this shape are the
  standard way to represent correlated bursts in a service process; see
  Fischer & Meier-Hellstern, "The Markov-modulated Poisson process (MMPP)
  cookbook", *Performance Evaluation* 18(2):149-171, 1993, §2, for the
  construction and its properties.
* Within a regime, each stage duration is drawn from a gamma distribution
  with a per-stage shape and a regime-dependent scale multiplier. Gamma is
  used because measured execution times in computing systems are positive,
  right-skewed and often heavy-tailed; see Harchol-Balter, *Performance
  Modeling and Design of Computer Systems*, Cambridge University Press 2013,
  Chapter 20, on heavy-tailed workload distributions and why an exponential
  fit understates the tail.
* An independent Bernoulli "interrupt" adds a spike to one stage, modelling
  a pre-emption the loop did not schedule.

This is a *model*, not a measurement. Nothing in these traces was recorded
from hardware, and nothing derived from them is a hardware number. The
purpose is a controlled benchmark where the ground-truth overrun labels are
known exactly, so a predictor's false-alarm and missed-overrun rates are
measurable rather than estimated.

Two families
------------
``TraceConfig.preset("jittery")``
    Weak regime persistence, heavy per-iteration jitter. Overruns are close
    to independent, so the past says little about the next iteration. This is
    the case in which a fixed threshold is expected to be hard to beat.

``TraceConfig.preset("bursty")``
    Strong regime persistence: once the loop is in a burst it tends to stay
    there for tens of iterations. History carries information, so a model with
    access to it has something to learn.

Determinism
-----------
All randomness comes from ``numpy.random.Generator(PCG64(seed))``. The same
seed gives the same trace on any platform NumPy supports.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from ..errors import ConfigurationError

__all__ = ["Trace", "TraceConfig", "generate_trace", "split_trace"]

_STAGES = ("sense", "estimate", "control", "actuate")


@dataclass(frozen=True)
class TraceConfig:
    """Parameters of a synthetic latency trace.

    Attributes
    ----------
    period_s:
        Loop period ``T`` [s], > 0. The deadline is implicit (``D = T``).
    n_iterations:
        Trace length, >= 50.
    stage_mean_s:
        Mean duration of each stage in the calm regime [s], four positive
        values summing to less than ``period_s``.
    stage_shape:
        Gamma shape ``k`` of each stage [-], four values > 0. Small ``k`` is a
        heavier tail; the gamma coefficient of variation is ``1/sqrt(k)``.
    burst_scale:
        Multiplier on every stage's scale in the burst regime [-], > 1.
    p_calm_to_burst, p_burst_to_calm:
        Markov transition probabilities in ``(0, 1)``. Expected burst length
        is ``1 / p_burst_to_calm`` iterations.
    interrupt_prob:
        Per-iteration probability of an added spike [-] in ``[0, 1)``.
    interrupt_mean_s:
        Mean of the exponential spike added on an interrupt [s], >= 0.
    label:
        Name carried into records.
    """

    period_s: float = 0.010
    n_iterations: int = 20000
    stage_mean_s: tuple[float, ...] = (0.0020, 0.0014, 0.0008, 0.0022)
    stage_shape: tuple[float, ...] = (6.0, 3.0, 9.0, 2.2)
    burst_scale: float = 2.1
    p_calm_to_burst: float = 0.02
    p_burst_to_calm: float = 0.25
    interrupt_prob: float = 0.012
    interrupt_mean_s: float = 0.0035
    label: str = "custom"

    def __post_init__(self) -> None:
        if not (self.period_s > 0.0):
            raise ConfigurationError(f"period_s must be > 0, got {self.period_s!r}")
        if self.n_iterations < 50:
            raise ConfigurationError(
                f"n_iterations must be >= 50, got {self.n_iterations!r}"
            )
        if len(self.stage_mean_s) != len(_STAGES) or len(self.stage_shape) != len(_STAGES):
            raise ConfigurationError(
                f"stage_mean_s and stage_shape must have {len(_STAGES)} entries"
            )
        if any(m <= 0.0 for m in self.stage_mean_s):
            raise ConfigurationError(f"stage_mean_s must be > 0, got {self.stage_mean_s!r}")
        if any(k <= 0.0 for k in self.stage_shape):
            raise ConfigurationError(f"stage_shape must be > 0, got {self.stage_shape!r}")
        if sum(self.stage_mean_s) >= self.period_s:
            raise ConfigurationError(
                f"calm-regime mean total {sum(self.stage_mean_s):.6g} s must be below the "
                f"period {self.period_s:.6g} s, or every iteration overruns"
            )
        if not (self.burst_scale > 1.0):
            raise ConfigurationError(f"burst_scale must be > 1, got {self.burst_scale!r}")
        for name, p in (
            ("p_calm_to_burst", self.p_calm_to_burst),
            ("p_burst_to_calm", self.p_burst_to_calm),
        ):
            if not (0.0 < p < 1.0):
                raise ConfigurationError(f"{name} must be in (0, 1), got {p!r}")
        if not (0.0 <= self.interrupt_prob < 1.0):
            raise ConfigurationError(
                f"interrupt_prob must be in [0, 1), got {self.interrupt_prob!r}"
            )
        if self.interrupt_mean_s < 0.0:
            raise ConfigurationError(
                f"interrupt_mean_s must be >= 0, got {self.interrupt_mean_s!r}"
            )

    @property
    def stationary_burst_probability(self) -> float:
        """Stationary probability of the burst regime [-].

        For a two-state chain with ``p = p_calm_to_burst`` and
        ``q = p_burst_to_calm`` the stationary distribution is
        ``(q, p) / (p + q)`` (standard result for an irreducible two-state
        chain; e.g. Ross, *Introduction to Probability Models*, 11th ed.,
        Academic Press 2014, §4.4).
        """
        p = self.p_calm_to_burst
        q = self.p_burst_to_calm
        return p / (p + q)

    @property
    def expected_burst_length(self) -> float:
        """Mean dwell time in the burst regime [iterations].

        Geometric with success probability ``p_burst_to_calm``, so the mean is
        ``1 / p_burst_to_calm``.
        """
        return 1.0 / self.p_burst_to_calm

    @classmethod
    def preset(cls, name: str, *, n_iterations: int = 20000) -> TraceConfig:
        """Named configuration: ``"jittery"`` or ``"bursty"``.

        Parameters
        ----------
        name:
            Preset name.
        n_iterations:
            Trace length.
        """
        if name == "jittery":
            return cls(
                n_iterations=n_iterations,
                stage_shape=(2.4, 1.5, 3.0, 1.2),
                burst_scale=1.35,
                p_calm_to_burst=0.16,
                p_burst_to_calm=0.62,
                interrupt_prob=0.035,
                interrupt_mean_s=0.0040,
                label="jittery",
            )
        if name == "bursty":
            return cls(
                n_iterations=n_iterations,
                stage_shape=(9.0, 6.0, 12.0, 5.0),
                burst_scale=2.6,
                p_calm_to_burst=0.010,
                p_burst_to_calm=0.055,
                interrupt_prob=0.004,
                interrupt_mean_s=0.0030,
                label="bursty",
            )
        raise ConfigurationError(f"unknown preset {name!r}; known: 'jittery', 'bursty'")


@dataclass
class Trace:
    """A generated latency trace and its ground truth.

    Attributes
    ----------
    config:
        The configuration that produced it.
    seed:
        Seed used.
    stage_s:
        ``(n, 4)`` per-stage durations [s].
    totals_s:
        ``(n,)`` per-iteration totals [s].
    regime:
        ``(n,)`` hidden regime, 0 calm and 1 burst. Ground truth, available
        to the generator and to nothing else: no predictor is given it.
    interrupted:
        ``(n,)`` boolean, whether an interrupt spike was added.
    """

    config: TraceConfig
    seed: int
    stage_s: np.ndarray
    totals_s: np.ndarray
    regime: np.ndarray
    interrupted: np.ndarray
    stage_names: tuple[str, ...] = field(default=_STAGES)

    @property
    def n(self) -> int:
        """Trace length [iterations]."""
        return int(self.totals_s.size)

    def overruns(self, deadline_s: float | None = None) -> np.ndarray:
        """Boolean ``(n,)``: ``totals_s > deadline_s`` (default the period)."""
        d = self.config.period_s if deadline_s is None else float(deadline_s)
        return self.totals_s > d

    @property
    def utilisation(self) -> float:
        """``E[d] / T`` [-], the loop's mean utilisation.

        For a single periodic task this is the quantity that bounds
        schedulability; the Pollaczek-Khinchine formula for M/D/1 waiting time
        (Kleinrock, *Queueing Systems, Volume 1: Theory*, Wiley 1975, §5.6)
        diverges as it approaches 1, which is the reason a loop at 0.9
        utilisation has a long overrun tail even when its mean fits.
        """
        return float(self.totals_s.mean() / self.config.period_s)


def generate_trace(config: TraceConfig, *, seed: int) -> Trace:
    """Generate a trace from ``config`` and ``seed``.

    Parameters
    ----------
    config:
        Trace parameters.
    seed:
        PCG64 seed. The same seed and config give the same trace.

    Returns
    -------
    Trace
        Durations, totals, hidden regime and interrupt flags.
    """
    rng = np.random.Generator(np.random.PCG64(int(seed)))
    n = config.n_iterations
    regime = np.zeros(n, dtype=np.int8)
    u = rng.random(n)
    state = 0
    for k in range(n):
        if state == 0:
            state = 1 if u[k] < config.p_calm_to_burst else 0
        else:
            state = 0 if u[k] < config.p_burst_to_calm else 1
        regime[k] = state
    scale_mult = np.where(regime == 1, config.burst_scale, 1.0)
    stage = np.empty((n, len(_STAGES)), dtype=np.float64)
    for j, (mean, shape) in enumerate(zip(config.stage_mean_s, config.stage_shape, strict=True)):
        base_scale = mean / shape
        stage[:, j] = rng.gamma(shape, base_scale * scale_mult)
    interrupted = rng.random(n) < config.interrupt_prob
    if config.interrupt_mean_s > 0.0:
        spikes = rng.exponential(config.interrupt_mean_s, size=n) * interrupted
        target = rng.integers(0, len(_STAGES), size=n)
        stage[np.arange(n), target] += spikes
    totals = stage.sum(axis=1)
    return Trace(
        config=config,
        seed=int(seed),
        stage_s=stage,
        totals_s=totals,
        regime=regime,
        interrupted=interrupted,
    )


def split_trace(trace: Trace, *, train_fraction: float = 0.6) -> tuple[Trace, Trace]:
    """Split a trace in time into train and test parts.

    The split is **chronological**, not random: a random split would leak the
    autocorrelation the predictors exist to exploit, and would flatter the
    learned model. Returns ``(train, test)``.

    Parameters
    ----------
    trace:
        Trace to split.
    train_fraction:
        Fraction of iterations in the training part, in ``(0, 1)``.
    """
    if not (0.0 < train_fraction < 1.0):
        raise ConfigurationError(
            f"train_fraction must be in (0, 1), got {train_fraction!r}"
        )
    cut = round(trace.n * train_fraction)
    if cut < 50 or trace.n - cut < 50:
        raise ConfigurationError(
            f"split leaves too few iterations: {cut} train, {trace.n - cut} test"
        )

    def _slice(lo: int, hi: int) -> Trace:
        from dataclasses import replace

        return Trace(
            config=replace(trace.config, n_iterations=hi - lo),
            seed=trace.seed,
            stage_s=trace.stage_s[lo:hi].copy(),
            totals_s=trace.totals_s[lo:hi].copy(),
            regime=trace.regime[lo:hi].copy(),
            interrupted=trace.interrupted[lo:hi].copy(),
        )

    return _slice(0, cut), _slice(cut, trace.n)
