"""Level-2 validation: Monte Carlo vs analytic BER across an SNR sweep.

For every modulation/channel case and SNR point, checks whether the analytic
BER lies inside the 95% Wilson confidence interval of a seeded Monte Carlo
estimate sized for >= ~150 expected errors. With a 95% interval, ~5% of
points are EXPECTED to fall outside; the honest acceptance criterion is
overall coverage consistent with 95%, not 100% membership.

Writes mc_vs_analytic_results.md next to this script. Runtime ~40 s.
"""

import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from berbench import analytic_ber, mc_ber, n_bits_for_target  # noqa: E402

OUT = Path(__file__).resolve().parent / "mc_vs_analytic_results.md"
N_CAP = 20_000_000
SEED = 20260801

CASES = [
    ("bpsk", {"channel": "awgn"}, np.arange(0.0, 11.0, 2.0)),
    ("ook", {"channel": "awgn"}, np.arange(0.0, 13.0, 2.0)),
    ("ook", {"channel": "awgn", "threshold": 0.4}, np.arange(0.0, 13.0, 2.0)),
    ("ppm", {"channel": "awgn", "M": 4}, np.arange(0.0, 11.0, 2.0)),
    ("ppm", {"channel": "awgn", "M": 16}, np.arange(0.0, 9.0, 2.0)),
    ("ook", {"channel": "lognormal", "sigma_i2": 0.1}, np.arange(0.0, 17.0, 4.0)),
    ("ook", {"channel": "lognormal", "sigma_i2": 0.3}, np.arange(0.0, 21.0, 4.0)),
    ("ook", {"channel": "lognormal", "sigma_i2": 0.3, "threshold": 0.5},
     np.arange(0.0, 21.0, 4.0)),
    ("bpsk", {"channel": "lognormal", "sigma_i2": 0.1}, np.arange(0.0, 13.0, 4.0)),
    ("ppm", {"channel": "lognormal", "sigma_i2": 0.2, "M": 4}, np.arange(0.0, 13.0, 4.0)),
]


def main() -> None:
    t0 = time.perf_counter()
    lines = [
        "# Monte Carlo vs analytic BER — validation run",
        "",
        f"Seed base: {SEED}; Wilson 95% CI; per-point n sized for >= ~150 expected "
        f"errors (cap {N_CAP:.0e} bits). Generated by mc_vs_analytic.py.",
        "",
        "| case | Eb/N0 dB | BER analytic | BER MC | errors | bits | Wilson 95% CI | "
        "analytic in CI |",
        "|---|---|---|---|---|---|---|---|",
    ]
    n_in = n_tot = 0
    for i, (mod, kw, snr) in enumerate(CASES):
        ana = analytic_ber(mod, snr, **kw).ber
        keep = ana > 150 / N_CAP
        n = int(min(N_CAP, n_bits_for_target(float(ana[keep].min()), 150)))
        mc = mc_ber(mod, snr[keep], n=n, seed=SEED + i, ci_level=0.95, **kw)
        name = mod + "".join(f" {k}={v}" for k, v in kw.items() if k != "channel")
        name += f" [{kw['channel']}]"
        for j, s in enumerate(mc.snr_db):
            a = ana[keep][j]
            inside = mc.ci_low[j] <= a <= mc.ci_high[j]
            n_in += inside
            n_tot += 1
            lines.append(
                f"| {name} | {s:g} | {a:.4e} | {mc.ber[j]:.4e} | {mc.n_errors[j]} | "
                f"{mc.n_bits[j]} | [{mc.ci_low[j]:.4e}, {mc.ci_high[j]:.4e}] | "
                f"{'YES' if inside else 'NO'} |"
            )
    elapsed = time.perf_counter() - t0
    lines += [
        "",
        f"**Coverage: {n_in}/{n_tot} points ({100 * n_in / n_tot:.1f}%) have the analytic "
        f"BER inside the 95% Wilson CI.** Expected coverage for a correct implementation "
        f"is ~95% (binomial: {n_tot} trials, p=0.95 => 2-sigma range "
        f"{0.95 * n_tot - 2 * np.sqrt(n_tot * 0.95 * 0.05):.0f}"
        f"-{n_tot} points).",
        "",
        f"Total Monte Carlo wall time: {elapsed:.1f} s (budget: < 180 s).",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
