"""Deterministic synthetic dataset for the link-availability predictor.

What this is, and what it is not
--------------------------------
Every row is one contact opportunity.  The geometry is **real**: contacts are
computed by :mod:`constellink.contacts` from an ``sgp4``-propagated Walker
constellation and a ground-station set, so elevation, range and duration are
whatever the orbital dynamics produce.  The **label** -- did this contact
close at the required data rate -- is generated by the capacity models in
:mod:`constellink.capacity` driven by a latent weather and pointing state.

That makes this a self-consistency dataset, not an empirical one.  A model
trained here learns the capacity model this package already contains, plus the
observation noise placed between the latent state and the features.  It
cannot and does not demonstrate agreement with measured link outages.  The
value of the exercise is the *comparison method* -- calibration of three
predictors on identical splits -- not the absolute numbers.  See
``DATASET_CARD.md``.

Generative structure
--------------------
Per contact, with ``rng`` seeded from ``seed``:

1. a latent cloud optical depth ``tau`` is drawn from a Gamma distribution
   whose mean depends on the station's assigned climate regime, and a latent
   visibility is drawn log-normally and correlated with ``tau``;
2. a latent pointing error is drawn half-normally;
3. a latent turbulence fade in dB is drawn log-normally -- this term is
   deliberately NOT exposed as a feature, so it is irreducible aleatoric
   noise and no predictor can reach perfect accuracy.  Log-normal
   (equivalently Gaussian-in-dB) is the conventional weak-fluctuation model
   for intensity scintillation; see Andrews & Phillips 2005, "Laser Beam
   Propagation through Random Media", 2nd ed., SPIE Press, Ch. 9;
4. the achievable rate is evaluated from the appropriate capacity model with
   those realisations and compared with the *planned* rate for that link
   class.  The plan is defined without tuning: it is the clear-sky, zero
   pointing-error achievable rate of the same terminal at the WORST-CASE
   range of that link class -- the maximum supported ISL range, or the slant
   range at the elevation mask for a ground leg (``planned_rates``).  A
   contact closes when the realised geometry and weather beat what the
   worst-case plan assumed, which is the operational question a link plan
   actually asks;
5. the FEATURES are noisy observations of the latent state (a forecast is not
   a measurement), so there is a genuine information gap between what the
   predictor sees and what determines the label.

Feature vector (``FEATURE_NAMES``, index order is part of the contract)::

    0 climatology_prior         long-run success rate of this stratum   [-]
    1 max_elevation_deg         culmination elevation, 90 for an ISL    [deg]
    2 min_range_km              closest approach over the window        [km]
    3 duration_s                window duration                        [s]
    4 cloud_optical_depth_obs   noisy observation of latent tau         [-]
    5 visibility_km_obs         noisy observation of latent visibility  [km]
    6 pointing_jitter_urad_obs  noisy observation of pointing error     [urad]
    7 is_optical                1 for the optical terminal, else 0      [-]
    8 is_ground                 1 for a ground leg, else 0              [-]

Determinism: every array is produced from ``numpy.random.default_rng(seed)``
and the contact geometry is a pure function of the constellation definition
and the horizon, so ``generate_dataset(seed=k)`` is reproducible.  The
regression suite pins the resulting statistics (``tests/test_regression.py``).
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime, timedelta

import numpy as np

from .capacity import (
    OpticalTerminal,
    RfTerminal,
    kim_specific_attenuation_db_km,
    optical_link,
    rf_link,
    slant_path_attenuation_db,
)
from .constellation import GroundStation, walker_delta
from .contacts import all_contact_windows
from .frames import WGS84_A_KM
from .geometry import slant_range_at_elevation

__all__ = [
    "FEATURE_NAMES",
    "planned_rates",
    "N_FEATURES",
    "DatasetConfig",
    "LinkDataset",
    "default_rf_terminal",
    "default_optical_terminal",
    "default_stations",
    "generate_dataset",
    "stratify",
]

FEATURE_NAMES = (
    "climatology_prior",
    "max_elevation_deg",
    "min_range_km",
    "duration_s",
    "cloud_optical_depth_obs",
    "visibility_km_obs",
    "pointing_jitter_urad_obs",
    "is_optical",
    "is_ground",
)
N_FEATURES = len(FEATURE_NAMES)

# Per-station climate regime: mean latent cloud optical depth [-] and mean
# latent visibility [km].  These are modelling inputs chosen to span a clear
# site and a cloudy one; they are not measured climatologies for the named
# locations and must not be read as such.
_CLIMATE = {
    "clear": (0.6, 30.0),
    "mixed": (1.8, 15.0),
    "cloudy": (3.5, 8.0),
}


@dataclass(frozen=True)
class DatasetConfig:
    """Generator configuration (all fields have documented units).

    Attributes
    ----------
    n_total, n_planes, phasing_f : Walker parameters.
    inclination_deg, altitude_km : Walker shell geometry.
    horizon_hours : propagation horizon [h], > 0.
    step_s : contact-scan grid step [s], > 0.
    plan_backoff_db : deliberate backoff applied to the planned rate [dB],
        >= 0.  Zero means the plan assumes exactly the worst-case clear-sky
        rate (see ``planned_rates``).
    turbulence_sigma_db : standard deviation of the latent fade [dB], >= 0.
    obs_noise_scale : multiplicative spread of the feature observations
        relative to the latent value, >= 0.
    optical_fraction : fraction of contacts assigned the optical terminal,
        in [0, 1].
    seed : master seed.
    """

    n_total: int = 24
    n_planes: int = 4
    phasing_f: int = 1
    inclination_deg: float = 53.0
    altitude_km: float = 550.0
    horizon_hours: float = 18.0
    step_s: float = 60.0
    plan_backoff_db: float = 0.0
    turbulence_sigma_db: float = 3.0
    obs_noise_scale: float = 0.35
    optical_fraction: float = 0.5
    seed: int = 20260401

    def __post_init__(self) -> None:
        if self.horizon_hours <= 0.0:
            raise ValueError(f"horizon_hours must be > 0, got {self.horizon_hours}")
        if self.step_s <= 0.0:
            raise ValueError(f"step_s must be > 0, got {self.step_s}")
        if self.plan_backoff_db < 0.0:
            raise ValueError(f"plan_backoff_db must be >= 0, got {self.plan_backoff_db}")
        if self.turbulence_sigma_db < 0.0:
            raise ValueError(
                f"turbulence_sigma_db must be >= 0, got {self.turbulence_sigma_db}")
        if self.obs_noise_scale < 0.0:
            raise ValueError(f"obs_noise_scale must be >= 0, got {self.obs_noise_scale}")
        if not 0.0 <= self.optical_fraction <= 1.0:
            raise ValueError(
                f"optical_fraction must be in [0, 1], got {self.optical_fraction}")


@dataclass(frozen=True)
class LinkDataset:
    """Generated dataset.

    Attributes
    ----------
    x : features, shape ``(n, N_FEATURES)``.
    y : binary labels (1 = contact closed at the required rate), shape ``(n,)``.
    stratum : integer stratum id per row, used by the climatology baseline.
    group : contact-opportunity group label (link name) for grouped splitting.
    feature_names : ``FEATURE_NAMES``.
    """

    x: np.ndarray
    y: np.ndarray
    stratum: np.ndarray
    group: np.ndarray
    feature_names: tuple[str, ...] = FEATURE_NAMES

    def __post_init__(self) -> None:
        n = self.x.shape[0]
        if self.x.shape[1] != N_FEATURES:
            raise ValueError(
                f"x must have {N_FEATURES} columns, got {self.x.shape[1]}")
        for name, arr in (("y", self.y), ("stratum", self.stratum),
                          ("group", self.group)):
            if arr.shape[0] != n:
                raise ValueError(f"{name} must have {n} rows, got {arr.shape[0]}")
        if not np.all(np.isin(self.y, (0, 1))):
            raise ValueError("y must be binary 0/1")

    def __len__(self) -> int:
        return int(self.x.shape[0])

    @property
    def base_rate(self) -> float:
        """Overall fraction of closed contacts [-]."""
        return float(self.y.mean())


def default_rf_terminal() -> RfTerminal:
    """A Ka-band terminal pair used by the generator.

    Every figure is a stated modelling assumption, not a measured
    specification of any real terminal: 3 dBW transmit power, 30 dBi antenna
    gain, 15 dB/K receive figure of merit, 26 GHz carrier, 500 MHz bandwidth,
    4.5 dB required Eb/N0, 2 dB of lumped other loss and 3 dB of margin.
    26 GHz and 500 MHz sit inside the Ka-band space-research allocations, which
    is why they were chosen; the power and gain figures are round numbers.
    """
    return RfTerminal(tx_power_dbw=3.0, tx_gain_dbi=30.0, rx_g_over_t_db_per_k=15.0,
                      frequency_hz=26.0e9, bandwidth_hz=500.0e6,
                      required_ebn0_db=4.5, tx_loss_db=1.0, other_loss_db=2.0,
                      margin_db=3.0)


def default_optical_terminal() -> OpticalTerminal:
    """A 1550 nm terminal pair used by the generator.

    Stated modelling assumptions, not a device datasheet: 1 W transmit power,
    1550 nm, 40 urad full divergence, 80 mm receive aperture, 500 photons per
    bit receiver sensitivity, 2 dB of optics loss each end, 3 dB margin.  The
    500 photons/bit figure is a deliberately conservative round number for a
    direct-detection receiver and is treated as an input, not a result.
    """
    return OpticalTerminal(tx_power_w=1.0, wavelength_m=1550e-9,
                           beam_divergence_full_rad=40e-6,
                           rx_aperture_diameter_m=0.08, photons_per_bit=500.0,
                           tx_optics_loss_db=2.0, rx_optics_loss_db=2.0,
                           margin_db=3.0)


def default_stations() -> list[GroundStation]:
    """Three ground stations spanning latitudes and climate regimes.

    Coordinates are rounded to 0.01 deg and are used only to produce varied
    pass geometry; the climate regime attached to each is a modelling choice
    (see ``_CLIMATE``), not a published climatology.
    """
    return [
        GroundStation("SVALBARD", 78.23, 15.41, 0.46, 10.0),
        GroundStation("SANTIAGO", -33.15, -70.67, 0.73, 10.0),
        GroundStation("AWARUA", -46.53, 168.38, 0.01, 10.0),
        GroundStation("SINGAPORE", 1.35, 103.82, 0.02, 10.0),
        GroundStation("GOLDSTONE", 35.43, -116.89, 1.03, 10.0),
    ]


_STATION_CLIMATE = {"SVALBARD": "cloudy", "SANTIAGO": "clear", "AWARUA": "mixed",
                    "SINGAPORE": "cloudy", "GOLDSTONE": "clear"}


def stratify(max_elevation_deg: np.ndarray, is_optical: np.ndarray,
             is_ground: np.ndarray) -> np.ndarray:
    """Stratum id from link type and elevation band.

    Strata are the cross product of ``{RF, optical} x {ISL, ground}`` and,
    for ground legs, the elevation bands ``[10, 25)``, ``[25, 50)``,
    ``[50, 90]`` deg.  The climatology baseline predicts the training base
    rate of the row's stratum, which is the standard "what does this kind of
    contact usually do" forecast.
    """
    bands = np.digitize(max_elevation_deg, [25.0, 50.0])
    base = is_optical.astype(int) * 2 + is_ground.astype(int)
    return (base * 3 + np.where(is_ground > 0, bands, 0)).astype(int)


def planned_rates(cfg: DatasetConfig,
                  isl_max_range_km: float = 5000.0,
                  ground_mask_deg: float = 10.0) -> dict[tuple[int, int], float]:
    """Planned rate [bit/s] per ``(is_optical, is_ground)`` link class.

    The plan is the clear-sky, zero-pointing-error achievable rate of the
    same terminal at the worst-case range of the class, reduced by
    ``cfg.plan_backoff_db``:

    * ISL: ``isl_max_range_km``, the maximum range the contact scan allows;
    * ground: the slant range at the elevation mask,
      :func:`~constellink.geometry.slant_range_at_elevation`.

    No figure here is fitted to the generated labels; the plan is a function
    of the terminal definitions and the geometry alone.  This matters, because
    choosing a threshold to balance the classes would make the subsequent
    calibration comparison meaningless.
    """
    rf = default_rf_terminal()
    opt = default_optical_terminal()
    r_orbit = WGS84_A_KM + cfg.altitude_km
    r_ground = slant_range_at_elevation(r_orbit, ground_mask_deg)
    backoff = 10.0 ** (-cfg.plan_backoff_db / 10.0)
    out: dict[tuple[int, int], float] = {}
    for is_opt in (0, 1):
        for is_gnd in (0, 1):
            rng_km = r_ground if is_gnd else isl_max_range_km
            if is_opt:
                rate = optical_link(rng_km, opt).achievable_rate_bps
            else:
                rate = rf_link(rng_km, rf).achievable_rate_bps
            out[(is_opt, is_gnd)] = rate * backoff
    return out


def generate_dataset(config: DatasetConfig | None = None) -> LinkDataset:
    """Generate the dataset described in the module docstring.

    Compute: one Walker propagation plus one contact scan, then a closed-form
    capacity evaluation per contact.  For the default 24-satellite, 6 hour,
    60 s configuration this runs in a few seconds on one core.
    """
    cfg = config or DatasetConfig()
    rng = np.random.default_rng(cfg.seed)
    epoch = datetime(2026, 4, 1, tzinfo=UTC)
    const = walker_delta(cfg.n_total, cfg.n_planes, cfg.phasing_f,
                         cfg.inclination_deg, cfg.altitude_km, epoch,
                         max_epoch_age_days=max(1.0, cfg.horizon_hours / 24.0 + 1.0))
    stations = default_stations()
    eph = const.ephemeris(epoch, epoch + timedelta(hours=cfg.horizon_hours), cfg.step_s)
    windows = all_contact_windows(eph, const.satellites, stations)
    if not windows:
        raise RuntimeError(
            "contact scan produced no windows; widen the horizon or relax the range limits")

    rf = default_rf_terminal()
    opt = default_optical_terminal()
    plan = planned_rates(cfg)

    n = len(windows)
    is_optical = (rng.random(n) < cfg.optical_fraction).astype(float)
    is_ground = np.array([1.0 if w.kind == "ground" else 0.0 for w in windows])
    max_el = np.array([w.max_elevation_deg if w.max_elevation_deg is not None else 90.0
                       for w in windows])
    min_rng = np.array([w.min_range_km for w in windows])
    dur = np.array([w.duration_s for w in windows])
    groups = np.array([f"{w.node_a}|{w.node_b}" for w in windows])

    # Latent weather state.  ISLs are above the atmosphere, so their latent
    # weather is irrelevant and set to the clear-sky limit.
    tau = np.empty(n)
    vis = np.empty(n)
    for i, w in enumerate(windows):
        if w.kind == "ground":
            regime = _STATION_CLIMATE.get(w.node_b, "mixed")
            mean_tau, mean_vis = _CLIMATE[regime]
            tau[i] = rng.gamma(shape=2.0, scale=mean_tau / 2.0)
            # Visibility is anti-correlated with optical depth.
            vis[i] = float(np.clip(
                rng.lognormal(np.log(mean_vis), 0.4) * np.exp(-0.25 * tau[i]),
                0.05, 100.0))
        else:
            tau[i] = 0.0
            vis[i] = 100.0

    # Latent pointing error [rad], half-normal with a 3 urad scale.
    point_err = np.abs(rng.normal(0.0, 3.0e-6, size=n))
    # Latent turbulence/scintillation fade [dB], log-normal in intensity.
    fade_db = np.abs(rng.normal(0.0, cfg.turbulence_sigma_db, size=n))

    y = np.zeros(n, dtype=int)
    for i in range(n):
        ground = is_ground[i] > 0.0
        if is_optical[i] > 0.0:
            term = OpticalTerminal(
                tx_power_w=opt.tx_power_w, wavelength_m=opt.wavelength_m,
                beam_divergence_full_rad=opt.beam_divergence_full_rad,
                rx_aperture_diameter_m=opt.rx_aperture_diameter_m,
                photons_per_bit=opt.photons_per_bit,
                pointing_error_rad=float(point_err[i]),
                tx_optics_loss_db=opt.tx_optics_loss_db,
                rx_optics_loss_db=opt.rx_optics_loss_db, margin_db=opt.margin_db)
            atm_db = 0.0
            if ground:
                beta = kim_specific_attenuation_db_km(float(vis[i]), 1550.0)
                # 2 km equivalent boundary-layer path at zenith (modelling
                # choice, stated), scaled to the slant path.
                zenith_db = beta * 2.0
                atm_db = slant_path_attenuation_db(zenith_db, float(max_el[i]))
            res_rate = optical_link(float(min_rng[i]), term,
                                    atmospheric_loss_db=atm_db + float(fade_db[i])
                                    ).achievable_rate_bps
        else:
            extra_db = 0.0
            if ground:
                # Gaseous plus cloud excess attenuation at Ka band, taken as
                # proportional to the latent optical depth (a proxy, stated as
                # such: it is not an ITU-R cloud-attenuation model).
                zenith_db = 0.3 + 0.4 * float(tau[i])
                extra_db = slant_path_attenuation_db(zenith_db, float(max_el[i]))
            res_rate = rf_link(float(min_rng[i]), rf,
                               extra_loss_db=extra_db + float(fade_db[i])
                               ).achievable_rate_bps
        y[i] = int(res_rate >= plan[(int(is_optical[i]), int(is_ground[i]))])

    # Features: noisy observations of the latent state.
    s = cfg.obs_noise_scale
    tau_obs = np.clip(tau * rng.lognormal(0.0, s, size=n), 0.0, 50.0)
    vis_obs = np.clip(vis * rng.lognormal(0.0, s, size=n), 0.01, 200.0)
    point_obs = np.clip(point_err * 1e6 * rng.lognormal(0.0, s, size=n), 0.0, 100.0)

    stratum = stratify(max_el, is_optical, is_ground)
    prior = np.empty(n)
    for sid in np.unique(stratum):
        m = stratum == sid
        prior[m] = y[m].mean()

    x = np.column_stack([prior, max_el, min_rng, dur, tau_obs, vis_obs,
                         point_obs, is_optical, is_ground])
    return LinkDataset(x=x, y=y, stratum=stratum, group=groups)
