"""Deadline arithmetic, percentiles and overrun accounting.

The overrun hand count in :func:`test_overrun_hand_counted_sequence` is the
Level 3 validation requirement "overrun accounting reproduces a hand-counted
overrun sequence exactly". The count is worked out in the comment, not
generated by the code under test.
"""

from __future__ import annotations

import math

import numpy as np
import pytest

from hilforge.errors import ConfigurationError, TimebaseRegressionError
from hilforge.timing import (
    LatencyHistogram,
    MonotonicGuard,
    PeriodSpec,
    overrun_report,
    quantile_standard_error,
    timing_uncertainty,
)

# The hand-counted trace. Period T = 0.010 s, implicit deadline D = T.
HAND_TRACE = [
    0.004,
    0.012,
    0.003,
    0.011,
    0.011,
    0.002,
    0.009,
    0.010,
    0.0101,
    0.005,
    0.016,
    0.006,
    0.003,
]
HAND_PERIOD = 0.010

# ---------------------------------------------------------------------------
# Hand count, worked out by hand before the code was run.
#
# DIRECT definition: d[i] > D = 0.010.
#   i=0  0.0040  no       i=7  0.0100  no  (equal is a met deadline)
#   i=1  0.0120  YES      i=8  0.0101  YES
#   i=2  0.0030  no       i=9  0.0050  no
#   i=3  0.0110  YES      i=10 0.0160  YES
#   i=4  0.0110  YES      i=11 0.0060  no
#   i=5  0.0020  no       i=12 0.0030  no
#   i=6  0.0090  no
#   -> direct overruns at [1, 3, 4, 8, 10], count 5.
#
# CASCADE definition: r[i] = i*T, s[i] = max(r[i], c[i-1]), c[i] = s[i] + d[i],
# D[i] = r[i] + T, overrun iff c[i] > D[i]. c[-1] = 0.
#   i=0  r=0.000 s=0.0000 c=0.0040  D=0.010  no
#   i=1  r=0.010 s=0.0100 c=0.0220  D=0.020  YES
#   i=2  r=0.020 s=0.0220 c=0.0250  D=0.030  no
#   i=3  r=0.030 s=0.0300 c=0.0410  D=0.040  YES
#   i=4  r=0.040 s=0.0410 c=0.0520  D=0.050  YES   <- late because i=3 was late
#   i=5  r=0.050 s=0.0520 c=0.0540  D=0.060  no
#   i=6  r=0.060 s=0.0600 c=0.0690  D=0.070  no
#   i=7  r=0.070 s=0.0700 c=0.0800  D=0.080  no    <- exactly on the deadline
#   i=8  r=0.080 s=0.0800 c=0.0901  D=0.090  YES
#   i=9  r=0.090 s=0.0901 c=0.0951  D=0.100  no
#   i=10 r=0.100 s=0.1000 c=0.1160  D=0.110  YES
#   i=11 r=0.110 s=0.1160 c=0.1220  D=0.120  YES   <- d=0.006 < D, late anyway
#   i=12 r=0.120 s=0.1220 c=0.1250  D=0.130  no
#   -> cascade overruns at [1, 3, 4, 8, 10, 11], count 6.
#   -> longest consecutive run 2, first starting at index 3.
# ---------------------------------------------------------------------------


def test_overrun_hand_counted_sequence():
    account = overrun_report(HAND_TRACE, HAND_PERIOD)
    assert account.direct_indices == [1, 3, 4, 8, 10]
    assert account.direct_count == 5
    assert account.cascade_indices == [1, 3, 4, 8, 10, 11]
    assert account.cascade_count == 6
    assert account.max_consecutive_cascade == 2
    assert account.first_cascade_run_start == 3
    assert account.n_iterations == 13


def test_overrun_hand_counted_completions():
    account = overrun_report(HAND_TRACE, HAND_PERIOD)
    expected = [
        0.0040,
        0.0220,
        0.0250,
        0.0410,
        0.0520,
        0.0540,
        0.0690,
        0.0800,
        0.0901,
        0.0951,
        0.1160,
        0.1220,
        0.1250,
    ]
    assert np.allclose(account.completion_s, expected, atol=1e-12)


def test_equality_is_not_an_overrun():
    account = overrun_report([0.010, 0.010, 0.010], 0.010)
    assert account.direct_count == 0
    assert account.cascade_count == 0


def test_cascade_diverges_from_direct():
    # A single long iteration pushes a short one past its deadline.
    account = overrun_report([0.016, 0.006, 0.003], 0.010)
    assert account.direct_indices == [0]
    assert account.cascade_indices == [0, 1]


def test_overrun_rates_and_dict():
    account = overrun_report(HAND_TRACE, HAND_PERIOD)
    assert account.direct_rate == pytest.approx(5 / 13)
    assert account.cascade_rate == pytest.approx(6 / 13)
    as_dict = account.as_dict()
    assert as_dict["direct_overrun_count"] == 5
    assert as_dict["cascade_overrun_count"] == 6
    assert as_dict["period_s"] == HAND_PERIOD


def test_overrun_report_rejects_bad_input():
    with pytest.raises(ConfigurationError):
        overrun_report([0.001], 0.0)
    with pytest.raises(ValueError):
        overrun_report([-0.001], 0.010)
    with pytest.raises(ValueError):
        overrun_report([math.nan], 0.010)
    with pytest.raises(ConfigurationError):
        overrun_report([0.001], 0.010, deadline_s=0.020)


def test_empty_trace_gives_nan_rates():
    account = overrun_report([], 0.010)
    assert account.n_iterations == 0
    assert math.isnan(account.direct_rate)


def test_period_spec_defaults_and_arithmetic():
    spec = PeriodSpec(period_s=0.004)
    assert spec.effective_deadline_s == 0.004
    assert spec.rate_hz == pytest.approx(250.0)
    assert spec.release_time_s(3) == pytest.approx(0.012)
    assert spec.absolute_deadline_s(3) == pytest.approx(0.016)
    with pytest.raises(ConfigurationError):
        spec.release_time_s(-1)


def test_period_spec_validation():
    with pytest.raises(ConfigurationError):
        PeriodSpec(period_s=0.0)
    with pytest.raises(ConfigurationError):
        PeriodSpec(period_s=0.01, deadline_s=0.02)
    with pytest.raises(ConfigurationError):
        PeriodSpec(period_s=0.01, deadline_s=0.0)
    with pytest.raises(ConfigurationError):
        PeriodSpec(period_s=0.01, cascade_limit=-1)


def test_monotonic_guard_accepts_increasing_and_rejects_a_step_back():
    guard = MonotonicGuard()
    for t in (0.0, 1.0, 1.0, 2.5):
        guard.check(t)
    assert guard.last == 2.5
    with pytest.raises(TimebaseRegressionError) as exc:
        guard.check(2.4999)
    assert "stepped backwards" in str(exc.value)


def test_monotonic_guard_tolerance_clamps_small_dips():
    guard = MonotonicGuard(tolerance_s=1e-6)
    guard.check(1.0)
    assert guard.check(1.0 - 5e-7) == 1.0
    assert guard.clamped == 1
    with pytest.raises(TimebaseRegressionError):
        guard.check(1.0 - 5e-6)
    guard.reset()
    assert guard.last is None and guard.clamped == 0


def test_monotonic_guard_rejects_non_finite():
    guard = MonotonicGuard()
    with pytest.raises(TimebaseRegressionError):
        guard.check(math.nan)


def test_monotonic_guard_validates_tolerance():
    with pytest.raises(ConfigurationError):
        MonotonicGuard(tolerance_s=-1e-9)


def test_histogram_percentiles_known_answer():
    # Samples 1..10 s. Hyndman & Fan type 1 (nearest rank): Q(p) = x_ceil(n p).
    #   p=0.50 -> ceil(5.0)  = 5  -> 5.0
    #   p=0.90 -> ceil(9.0)  = 9  -> 9.0
    #   p=0.95 -> ceil(9.5)  = 10 -> 10.0
    # Type 7 (linear): h = (n-1)p + 1.
    #   p=0.50 -> h = 5.5  -> 5 + 0.5*(6-5)   = 5.5
    #   p=0.90 -> h = 9.1  -> 9 + 0.1*(10-9)  = 9.1
    hist = LatencyHistogram()
    hist.extend(np.arange(1, 11, dtype=float))
    assert hist.percentile(0.50, method="nearest_rank") == 5.0
    assert hist.percentile(0.90, method="nearest_rank") == 9.0
    assert hist.percentile(0.95, method="nearest_rank") == 10.0
    assert hist.percentile(0.50, method="linear") == pytest.approx(5.5)
    assert hist.percentile(0.90, method="linear") == pytest.approx(9.1)
    assert hist.percentile(0.0) == 1.0
    assert hist.percentile(1.0) == 10.0


def test_histogram_moments_known_answer():
    # 1..10: mean 5.5, sample stdev sqrt(55/6) = 3.0276503541.
    hist = LatencyHistogram()
    hist.extend(np.arange(1, 11, dtype=float))
    assert hist.count == 10
    assert hist.mean == pytest.approx(5.5)
    assert hist.stdev == pytest.approx(math.sqrt(55.0 / 6.0), rel=1e-12)
    assert hist.minimum == 1.0
    assert hist.maximum == 10.0


def test_histogram_matches_numpy_linear_percentile():
    rng = np.random.default_rng(7)
    data = rng.lognormal(mean=-8.0, sigma=0.6, size=5000)
    hist = LatencyHistogram()
    hist.extend(data)
    for p in (0.1, 0.5, 0.9, 0.99):
        assert hist.percentile(p, method="linear") == pytest.approx(
            float(np.percentile(data, 100 * p)), rel=1e-12
        )


def test_binned_histogram_error_is_bounded_by_one_bin():
    rng = np.random.default_rng(11)
    data = rng.exponential(1e-3, size=20000)
    exact = LatencyHistogram()
    binned = LatencyHistogram(mode="binned", bin_width_s=1e-5, n_bins=4096)
    exact.extend(data)
    binned.extend(data)
    assert binned.binned_percentile_error_bound_s() == 1e-5
    assert exact.binned_percentile_error_bound_s() == 0.0
    for p in (0.5, 0.9, 0.99):
        diff = binned.percentile(p) - exact.percentile(p)
        assert 0.0 <= diff <= 1e-5


def test_binned_histogram_counts_overflow():
    hist = LatencyHistogram(mode="binned", bin_width_s=1e-3, n_bins=4)
    hist.extend([1e-4, 5e-3, 2e-3])
    assert hist.overflow == 1
    assert hist.count == 3
    assert hist.samples().size == 0


def test_histogram_validation():
    hist = LatencyHistogram()
    with pytest.raises(ValueError):
        hist.add(-1.0)
    with pytest.raises(ValueError):
        hist.add(math.inf)
    with pytest.raises(ValueError):
        hist.percentile(0.5)
    with pytest.raises(ConfigurationError):
        LatencyHistogram(mode="approximate")
    with pytest.raises(ConfigurationError):
        LatencyHistogram(bin_width_s=0.0)
    with pytest.raises(ConfigurationError):
        LatencyHistogram(n_bins=0)
    hist.add(1.0)
    with pytest.raises(ConfigurationError):
        hist.percentile(1.5)
    with pytest.raises(ConfigurationError):
        hist.percentile(0.5, method="midpoint")


def test_histogram_summary_keys():
    hist = LatencyHistogram()
    hist.extend(np.linspace(1e-4, 1e-3, 1000))
    summary = hist.summary()
    for key in ("count", "mean_s", "stdev_s", "min_s", "max_s", "p50_s", "p90_s", "p99_s"):
        assert key in summary


def test_quantile_standard_error_known_answer():
    # p=0.5, n=10000, f=2.0 -> sqrt(0.25/10000)/2 = 0.005/2 = 0.0025.
    assert quantile_standard_error(0.5, 10000, 2.0) == pytest.approx(0.0025, rel=1e-12)
    with pytest.raises(ConfigurationError):
        quantile_standard_error(0.0, 100, 1.0)
    with pytest.raises(ConfigurationError):
        quantile_standard_error(0.5, 0, 1.0)
    with pytest.raises(ConfigurationError):
        quantile_standard_error(0.5, 100, 0.0)


def test_timing_uncertainty_known_answer():
    # Four identical durations: stdev 0, so u_A = 0 and u_c = u_B.
    # u_B = delta / sqrt(6 n) = 1e-6 / sqrt(24) = 2.0412415e-07 s.
    unc = timing_uncertainty([1e-3] * 4, resolution_s=1e-6, call_overhead_s=5e-8)
    assert unc.n == 4
    assert unc.u_statistical_s == pytest.approx(0.0)
    assert unc.u_resolution_s == pytest.approx(2.0412414523e-07, rel=1e-9)
    assert unc.combined_s == pytest.approx(unc.u_resolution_s)
    assert unc.expanded_k2_s == pytest.approx(2.0 * unc.combined_s)
    assert unc.call_overhead_s == 5e-8
    assert "JCGM" not in unc.as_text()  # the citation lives in the docstring
    assert "u_c combined" in unc.as_text()


def test_timing_uncertainty_validation():
    with pytest.raises(ConfigurationError):
        timing_uncertainty([1e-3], resolution_s=1e-6)
    with pytest.raises(ConfigurationError):
        timing_uncertainty([1e-3, 1e-3], resolution_s=0.0)
    with pytest.raises(ConfigurationError):
        timing_uncertainty([1e-3, 1e-3], resolution_s=1e-6, call_overhead_s=-1.0)
    with pytest.raises(ValueError):
        timing_uncertainty([1e-3, math.nan], resolution_s=1e-6)
