"""Validation: anomaly detector benchmark on a labeled synthetic fault set.

Compares the classical baseline (per-band log-energy z-score, fitted
first) against the MLP autoencoder-equivalent NominalModel, on the
same features, the same threshold rule (q0.995 of held-out nominal
scores), and the same labeled test set.

Test set (all generated by committed seeded code, see
src/jitterscope/telemetry.py and DATASET_CARD.md):
  - 6 nominal records (no faults)          -> all windows labeled 0
  - 6 new-tone records                     -> windows after t_start = 1
  - 6 band-energy-shift records            -> windows after t_start = 1
  - 6 transient-burst records              -> windows containing a burst = 1

Window labeling convention: a window is positive if ANY sample inside
it is marked by the generator's fault mask. Windows are 1 s with 50 %
overlap, so a fault onset contaminates at most one otherwise-nominal
window; that window is counted as positive.

Metrics: precision = TP/(TP+FP), recall = TP/(TP+FN),
F1 = 2PR/(P+R) at the fixed operating threshold, plus ROC AUC
(threshold-free ranking quality) computed with sklearn.

Rerun:  python validation/val_detector.py   (runtime ~1 min, 2 CPU)
"""

import sys
import time
from pathlib import Path

import numpy as np
from sklearn.metrics import roc_auc_score

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from jitterscope import (  # noqa: E402
    BandZScoreBaseline,
    FeatureExtractor,
    NominalModel,
    detect,
    generate_telemetry,
)

FS = 1000.0
DURATION = 60.0
WINDOW_S = 1.0
N_TRAIN_RECORDS = 4
N_PER_CLASS = 6
TRAIN_SEEDS = [1000 + i for i in range(N_TRAIN_RECORDS)]

lines: list[str] = []


def log(msg: str = "") -> None:
    lines.append(msg)


def fault_specs(kind: str, i: int) -> list[dict]:
    """Deterministic per-record fault parameters (varied but seeded)."""
    if kind == "nominal":
        return []
    if kind == "new_tone":
        return [{"kind": "new_tone", "t_start": 30.0,
                 "freq_hz": 120.0 + 15.0 * i, "rms": 0.6e-6}]
    if kind == "band_shift":
        return [{"kind": "band_shift", "t_start": 30.0, "f_lo": 150.0 + 20.0 * i,
                 "f_hi": 250.0 + 20.0 * i, "factor": 4.0 + i}]
    if kind == "transient":
        return [{"kind": "transient", "t_start": 30.0, "rate_hz": 0.8,
                 "amp": (3.0 + 0.5 * i) * 1e-6, "decay_s": 0.05, "ring_hz": 120.0}]
    raise ValueError(kind)


def window_labels(mask: np.ndarray, centers: np.ndarray) -> np.ndarray:
    """Positive if any sample in the window carries the fault mask."""
    half = int(round(0.5 * WINDOW_S * FS))
    out = np.zeros(centers.size, dtype=int)
    for i, c in enumerate(centers):
        j = int(round(c * FS))
        out[i] = int(mask[max(0, j - half): min(mask.size, j + half)].any())
    return out


def metrics(y_true: np.ndarray, y_pred: np.ndarray) -> tuple[float, float, float, int, int, int]:
    tp = int(np.sum((y_true == 1) & (y_pred == 1)))
    fp = int(np.sum((y_true == 0) & (y_pred == 1)))
    fn = int(np.sum((y_true == 1) & (y_pred == 0)))
    prec = tp / (tp + fp) if tp + fp else 0.0
    rec = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * prec * rec / (prec + rec) if prec + rec else 0.0
    return prec, rec, f1, tp, fp, fn


t_start_run = time.perf_counter()
log("=== jitterscope anomaly detector benchmark ===")
log(f"records: {DURATION:.0f} s @ {FS:.0f} Hz; windows {WINDOW_S:.1f} s, 50% overlap; "
    f"24 log-spaced PSD bins (1 Hz - Nyquist)")
log(f"training: {N_TRAIN_RECORDS} nominal records, seeds {TRAIN_SEEDS}")
log(f"test set: {N_PER_CLASS} records each of nominal / new_tone / band_shift / transient "
    f"(seeds 2000+)")
log("threshold rule (both models): q0.995 of held-out nominal scores")
log()

# --- fit on nominal training data -----------------------------------------
ext = FeatureExtractor(fs=FS, window_s=WINDOW_S)
train_feats = []
for s in TRAIN_SEEDS:
    _, x, _ = generate_telemetry(DURATION, FS, seed=s)
    f_, _ = ext.transform(x)
    train_feats.append(f_)
train_feats_arr = np.vstack(train_feats)
log(f"training feature matrix: {train_feats_arr.shape} (windows x bins)")

t0 = time.perf_counter()
baseline = BandZScoreBaseline(quantile=0.995).fit(train_feats_arr)
t_base = time.perf_counter() - t0
t0 = time.perf_counter()
mlp = NominalModel(seed=0, quantile=0.995).fit(train_feats_arr)
t_mlp = time.perf_counter() - t0
log(f"baseline fit: {t_base:.3f} s, threshold = {baseline.threshold_:.4f} (max |z|)")
log(f"MLP fit:      {t_mlp:.3f} s, threshold = {mlp.threshold_:.4f} (reconstruction MSE)")
log("MLP architecture: MLPRegressor(24 -> 16 -> 6 -> 16 -> 24), tanh, adam, "
    "alpha=1e-3, max_iter=3000, random_state=0")
log()

# --- build labeled test set ------------------------------------------------
kinds = ["nominal", "new_tone", "band_shift", "transient"]
per_kind: dict[str, dict[str, list]] = {
    k: {"y": [], "s_base": [], "s_mlp": [], "p_base": [], "p_mlp": [], "conf_mlp": []}
    for k in kinds
}
seed = 2000
for kind in kinds:
    for i in range(N_PER_CLASS):
        _, x, mask = generate_telemetry(DURATION, FS, seed=seed, faults=fault_specs(kind, i))
        seed += 1
        rb = detect(x, model=baseline, extractor=ext)
        rm = detect(x, model=mlp, extractor=ext)
        y = window_labels(mask, rb.window_centers_s)
        per_kind[kind]["y"].append(y)
        per_kind[kind]["s_base"].append(rb.scores)
        per_kind[kind]["s_mlp"].append(rm.scores)
        per_kind[kind]["p_base"].append(rb.flags.astype(int))
        per_kind[kind]["p_mlp"].append(rm.flags.astype(int))
        per_kind[kind]["conf_mlp"].append(rm.confidence)


def cat(kind: str, key: str) -> np.ndarray:
    return np.concatenate(per_kind[kind][key])


y_all = np.concatenate([cat(k, "y") for k in kinds])
pb_all = np.concatenate([cat(k, "p_base") for k in kinds])
pm_all = np.concatenate([cat(k, "p_mlp") for k in kinds])
sb_all = np.concatenate([cat(k, "s_base") for k in kinds])
sm_all = np.concatenate([cat(k, "s_mlp") for k in kinds])

log(f"test windows: {y_all.size} total, {int(y_all.sum())} faulty, "
    f"{int((y_all == 0).sum())} nominal")
log()
log("--- Overall metrics at the fixed q0.995 threshold ---")
log(f"{'model':>22} {'precision':>10} {'recall':>8} {'F1':>8} {'TP':>6} {'FP':>5} {'FN':>5} "
    f"{'ROC AUC':>9}")
results = {}
for name, pred, score in (("baseline band z-score", pb_all, sb_all),
                          ("MLP autoencoder", pm_all, sm_all)):
    prec, rec, f1, tp, fp, fn = metrics(y_all, pred)
    auc = roc_auc_score(y_all, score)
    results[name] = (prec, rec, f1, auc)
    log(f"{name:>22} {prec:10.4f} {rec:8.4f} {f1:8.4f} {tp:6d} {fp:5d} {fn:5d} {auc:9.4f}")
log()

log("--- Per-fault-type recall (fraction of faulty windows detected) ---")
log(f"{'fault type':>14} {'faulty windows':>15} {'baseline recall':>16} {'MLP recall':>12}")
for kind in kinds[1:]:
    y = cat(kind, "y")
    rb = cat(kind, "p_base")
    rm = cat(kind, "p_mlp")
    n_pos = int(y.sum())
    log(f"{kind:>14} {n_pos:15d} "
        f"{float(rb[y == 1].mean()):16.4f} {float(rm[y == 1].mean()):12.4f}")
log()

log("--- False-alarm rate on the 6 purely nominal test records ---")
yn = cat("nominal", "y")
log(f"  nominal windows: {yn.size} (all labeled 0)")
log(f"  baseline false alarms: {int(cat('nominal', 'p_base').sum())} "
    f"({float(cat('nominal', 'p_base').mean()) * 100:.2f} %)")
log(f"  MLP false alarms:      {int(cat('nominal', 'p_mlp').sum())} "
    f"({float(cat('nominal', 'p_mlp').mean()) * 100:.2f} %)")
log("  (design expectation at q0.995 on unseen nominal data: ~0.5 %, higher if the")
log("   held-out calibration set under-represents nominal variability)")
log()

log("--- Confidence output (MLP empirical nominal-CDF) ---")
conf_nom = cat("nominal", "conf_mlp")
conf_flt = np.concatenate([cat(k, "conf_mlp") for k in kinds[1:]])
y_flt = np.concatenate([cat(k, "y") for k in kinds[1:]])
log(f"  mean confidence, nominal windows : {float(conf_nom.mean()):.4f}")
log(f"  mean confidence, faulty windows  : {float(conf_flt[y_flt == 1].mean()):.4f}")
log()

b_f1, m_f1 = results["baseline band z-score"][2], results["MLP autoencoder"][2]
b_auc, m_auc = results["baseline band z-score"][3], results["MLP autoencoder"][3]
log("--- Verdict ---")
if b_f1 > m_f1:
    log(f"The CLASSICAL BASELINE WINS on F1: {b_f1:.4f} vs {m_f1:.4f} for the MLP "
        f"(delta {b_f1 - m_f1:+.4f}).")
elif m_f1 > b_f1:
    log(f"The MLP wins on F1: {m_f1:.4f} vs {b_f1:.4f} for the baseline "
        f"(delta {m_f1 - b_f1:+.4f}).")
else:
    log(f"Tie on F1: both {b_f1:.4f}.")
log(f"ROC AUC: baseline {b_auc:.4f}, MLP {m_auc:.4f} "
    f"({'baseline' if b_auc > m_auc else 'MLP'} better by "
    f"{abs(b_auc - m_auc):.4f}).")
log("Interpretation: the synthetic faults are additive-energy signatures that raise")
log("log-PSD in specific bins, which is exactly the alternative hypothesis the z-score")
log("baseline is built for. The MLP has no structural advantage on this dataset and")
log("carries extra fit cost and hyperparameters. It is retained for the case of")
log("correlated multi-band shape changes that a per-bin marginal test cannot see;")
log("that case is NOT demonstrated here.")
log()
log(f"total benchmark runtime: {time.perf_counter() - t_start_run:.1f} s on 2 CPU cores")

out = Path(__file__).resolve().parent / "val_detector_output.txt"
out.write_text("\n".join(lines) + "\n")
print("\n".join(lines))
print(f"saved {out}")
