"""Roofline bound, device model validation, and the calibration fit."""

from __future__ import annotations

import numpy as np
import pytest

from edgeinfer.roofline import DeviceModel, calibrate_device, roofline_time_s


class TestDeviceModel:
    def test_ridge_point_is_peak_flops_over_peak_bandwidth(self) -> None:
        # Williams et al. 2009 section 3: 10 GFLOP/s over 5 GB/s -> 2 FLOP/B.
        device = DeviceModel("d", 10e9, 5e9)
        assert device.ridge_point_flops_per_byte == pytest.approx(2.0)

    def test_attainable_rate_is_the_min_of_the_two_roofs(self) -> None:
        device = DeviceModel("d", 10e9, 5e9)
        # Below the ridge: bandwidth-limited -> 5e9 * 1 = 5e9 FLOP/s.
        assert device.attainable_flops(1.0) == pytest.approx(5e9)
        # Above the ridge: compute-limited -> 10e9 FLOP/s.
        assert device.attainable_flops(100.0) == pytest.approx(10e9)
        # Exactly at the ridge both roofs agree.
        assert device.attainable_flops(2.0) == pytest.approx(10e9)

    def test_memory_bound_classification_follows_the_ridge(self) -> None:
        device = DeviceModel("d", 10e9, 5e9)
        assert device.is_memory_bound(1.9)
        assert not device.is_memory_bound(2.1)

    @pytest.mark.parametrize(
        ("kwargs", "match"),
        [
            ({"peak_flops": 0.0}, "peak_flops"),
            ({"peak_flops": -1.0}, "peak_flops"),
            ({"peak_flops": float("inf")}, "peak_flops"),
            ({"peak_bandwidth_bytes_s": 0.0}, "peak_bandwidth"),
            ({"overhead_per_node_s": -1e-9}, "overhead_per_node_s"),
            ({"fixed_overhead_s": -1e-9}, "fixed_overhead_s"),
            ({"name": ""}, "name"),
        ],
    )
    def test_invalid_parameters_are_rejected(self, kwargs: dict, match: str) -> None:
        base = {"name": "d", "peak_flops": 1e9, "peak_bandwidth_bytes_s": 1e9}
        base.update(kwargs)
        with pytest.raises(ValueError, match=match):
            DeviceModel(**base)

    def test_negative_intensity_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="negative"):
            DeviceModel("d", 1e9, 1e9).attainable_flops(-1.0)

    def test_scaling_records_the_factor_in_the_source(self) -> None:
        scaled = DeviceModel("d", 1e9, 1e9, source="declared").scaled(0.5)
        assert scaled.peak_flops == pytest.approx(5e8)
        assert "scaled by 0.5" in scaled.source

    def test_non_positive_scale_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="scale factor"):
            DeviceModel("d", 1e9, 1e9).scaled(0.0)


class TestRooflineTime:
    def test_known_answer_compute_bound(self) -> None:
        # 2e9 flops at 1 GFLOP/s = 2 s; 1e9 B at 1 GB/s = 1 s; max -> 2 s.
        device = DeviceModel("d", 1e9, 1e9)
        assert roofline_time_s(2e9, 1e9, device) == pytest.approx(2.0)

    def test_known_answer_memory_bound(self) -> None:
        device = DeviceModel("d", 1e9, 1e9)
        assert roofline_time_s(1e9, 4e9, device) == pytest.approx(4.0)

    def test_zero_work_takes_zero_time(self) -> None:
        assert roofline_time_s(0.0, 0.0, DeviceModel("d", 1e9, 1e9)) == 0.0

    def test_negative_work_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="non-negative"):
            roofline_time_s(-1.0, 0.0, DeviceModel("d", 1e9, 1e9))

    def test_the_bound_never_exceeds_the_attainable_rate_form(self) -> None:
        """The time form and the rate form of the roofline must agree."""
        device = DeviceModel("d", 3.2e9, 7.5e9)
        for flops, traffic in ((1e6, 2e5), (5e3, 9e6), (1e9, 1e9)):
            intensity = flops / traffic
            from_rate = flops / device.attainable_flops(intensity)
            assert roofline_time_s(flops, traffic, device) == pytest.approx(from_rate)


class TestCalibration:
    def _synthetic(self, n: int = 40, seed: int = 3, mix: bool = True):
        """A population whose latency is generated by a known device model.

        With ``mix=True`` the per-node arithmetic intensities straddle the
        device ridge point (2 GFLOP/s over 6 GB/s = 0.333 FLOP/B), so both
        roofs bind somewhere in the population and both peaks are
        identifiable. With ``mix=False`` every node is compute bound and the
        bandwidth is not identifiable at all, which is asserted separately.
        """
        rng = np.random.default_rng(seed)
        truth = DeviceModel("truth", 2.0e9, 6.0e9, overhead_per_node_s=3e-7,
                            fixed_overhead_s=5e-6)
        node_flops: list[float] = []
        node_bytes: list[float] = []
        index: list[int] = []
        measured: list[float] = []
        for g in range(n):
            k = int(rng.integers(2, 7))
            flops = 10.0 ** rng.uniform(2, 6, size=k)
            if mix:
                traffic = 10.0 ** rng.uniform(2, 6, size=k)
            else:
                traffic = flops / 10.0 ** rng.uniform(3, 4, size=k)
            total = float(
                np.sum(np.maximum(flops / truth.peak_flops,
                                  traffic / truth.peak_bandwidth_bytes_s))
            )
            measured.append(total + truth.overhead_per_node_s * k + truth.fixed_overhead_s)
            node_flops.extend(flops.tolist())
            node_bytes.extend(traffic.tolist())
            index.extend([g] * k)
        return (
            np.asarray(node_flops),
            np.asarray(node_bytes),
            np.asarray(index),
            np.asarray(measured),
            truth,
        )

    def test_calibration_recovers_a_known_device_model(self) -> None:
        nf, nb, idx, measured, truth = self._synthetic(n=60)
        fitted = calibrate_device(nf, nb, idx, measured, "fitted", grid=24)
        # The grid is log-spaced over four decades with 24 points, so the peak
        # spacing is 10**(4/23) ~ 1.49; recovery to within a factor of two is
        # the best the grid can do and is what is asserted.
        assert 0.5 < fitted.peak_flops / truth.peak_flops < 2.0
        assert 0.5 < fitted.peak_bandwidth_bytes_s / truth.peak_bandwidth_bytes_s < 2.0

    def test_bandwidth_is_not_identifiable_from_a_compute_bound_population(self) -> None:
        """A documented limitation, asserted rather than hidden.

        When every node in the calibration set is compute bound, the memory
        roof never binds and the fitted bandwidth carries no information: it
        lands wherever the grid search left it, here off the true value by
        three orders of magnitude in the *low* direction, which still never
        makes the memory roof bind. The fit reproduces the latencies it saw;
        it simply must not be read as a bandwidth measurement.
        """
        nf, nb, idx, measured, truth = self._synthetic(n=60, mix=False)
        fitted = calibrate_device(nf, nb, idx, measured, "fitted", grid=24)
        ratio = fitted.peak_bandwidth_bytes_s / truth.peak_bandwidth_bytes_s
        assert not 1 / 3 < ratio < 3, f"bandwidth ratio {ratio} looks identified"
        counts = np.bincount(idx).astype(float)
        per_node = np.maximum(nf / fitted.peak_flops, nb / fitted.peak_bandwidth_bytes_s)
        pred = (
            np.bincount(idx, weights=per_node)
            + fitted.overhead_per_node_s * counts
            + fitted.fixed_overhead_s
        )
        assert float(np.median(np.abs(pred - measured) / measured)) < 0.30

    def test_calibration_reproduces_the_latencies_it_was_fitted_on(self) -> None:
        nf, nb, idx, measured, _ = self._synthetic(n=60)
        fitted = calibrate_device(nf, nb, idx, measured, "fitted", grid=24)
        counts = np.bincount(idx).astype(float)
        per_node = np.maximum(nf / fitted.peak_flops, nb / fitted.peak_bandwidth_bytes_s)
        pred = (
            np.bincount(idx, weights=per_node)
            + fitted.overhead_per_node_s * counts
            + fitted.fixed_overhead_s
        )
        rel = np.abs(pred - measured) / measured
        assert float(np.median(rel)) < 0.15

    def test_the_fit_is_labelled_a_fit(self) -> None:
        nf, nb, idx, measured, _ = self._synthetic(n=8)
        fitted = calibrate_device(nf, nb, idx, measured, "fitted", grid=6)
        assert fitted.source == "calibrated-fit"

    def test_overheads_are_non_negative(self) -> None:
        nf, nb, idx, measured, _ = self._synthetic(n=12)
        fitted = calibrate_device(nf, nb, idx, measured, "fitted", grid=8)
        assert fitted.overhead_per_node_s >= 0.0
        assert fitted.fixed_overhead_s >= 0.0

    def test_too_few_graphs_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="at least 4 calibration graphs"):
            calibrate_device(
                np.ones(3), np.ones(3), np.arange(3), np.ones(3), "x"
            )

    def test_non_positive_latency_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="strictly positive"):
            calibrate_device(
                np.ones(4), np.ones(4), np.arange(4), np.zeros(4), "x"
            )

    def test_gapped_graph_index_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="no gaps"):
            calibrate_device(
                np.ones(4), np.ones(4), np.array([0, 1, 2, 7]), np.ones(4), "x"
            )

    def test_mismatched_lengths_are_rejected(self) -> None:
        with pytest.raises(ValueError, match="same length"):
            calibrate_device(np.ones(4), np.ones(3), np.arange(4), np.ones(4), "x")

    def test_negative_node_cost_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="non-negative"):
            calibrate_device(
                -np.ones(4), np.ones(4), np.arange(4), np.ones(4), "x"
            )

    def test_tiny_grid_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="grid must be >= 4"):
            calibrate_device(
                np.ones(4), np.ones(4), np.arange(4), np.ones(4), "x", grid=3
            )
