"""Afterpulsing as an excess-count process.

A single-photon avalanche diode traps carriers during an avalanche. A trapped
carrier released later triggers a second avalanche with no photon behind it.
The result is an extra count correlated with a real one, which is why
afterpulsing cannot be removed by subtracting a background rate: it scales with
the signal.

**The model implemented here is stated, not quoted.** It is a Poisson cluster
(compound Poisson) process, and the two accounting variants below are the two
that appear in detector datasheets, usually without saying which is meant:

*First order.* Each **registered** count produces at most one afterpulse, with
probability ``p``. Cluster size ``C`` in ``{1, 2}`` with ``P(C = 2) = p``:

    E[C] = 1 + p,      E[C^2] = 1 + 3p,
    m_obs = m_primary (1 + p),                                            (A1)
    Fano[N] = E[C^2]/E[C] = (1 + 3p) / (1 + p).

*Cascading.* An afterpulse can itself afterpulse, so ``C`` is geometric on
``{1, 2, ...}`` with ``P(C = c) = p^(c-1) (1 - p)``, requiring ``p < 1``:

    E[C] = 1/(1 - p),  Var[C] = p/(1 - p)^2,
    m_obs = m_primary / (1 - p),                                          (A2)
    Fano[N] = (1 + p) / (1 - p).

Both Fano expressions follow from the compound-Poisson identity
``Var[N] = mu E[C^2]``, ``E[N] = mu E[C]`` for ``K ~ Poisson(mu)`` primaries;
they are derived here and checked by Monte Carlo in
``validation/validate_afterpulse.py``. Afterpulsing is therefore the one
non-ideality in this package that pushes the Fano factor **above** 1, where
dead time pushes it below; the sign of the departure from 1 is a usable
diagnostic.

**Interaction with dead time, which is the part usually left out.** An
afterpulse whose release delay falls inside the detector's dead period is
suppressed. With release delays exponential with mean ``t_ap``, the fraction
surviving a dead time ``tau`` is ``exp(-tau / t_ap)``, so the *effective*
afterpulse probability a measurement sees is

    p_eff = p exp(-tau / t_ap).                                           (A3)

A detector quoted at ``p = 0.03`` with ``t_ap = 100 ns`` behind a 50 ns dead
time delivers ``p_eff = 0.0182``, not 0.03. (A3) assumes a single exponential
release; real SPADs show multi-exponential or power-law tails, which this
package does not model and the README lists as a limitation.

Units: rates in counts/s, ``tau`` and ``t_ap`` in s, probabilities
dimensionless. Validity: the counting window must be long compared with
``t_ap`` for clusters to be contained in it; the cluster-size distributions
above are untimed and say nothing about where inside a window the extra counts
land.
"""

from __future__ import annotations

from typing import Literal

import numpy as np

__all__ = [
    "AfterpulseModel",
    "cluster_size_moments",
    "effective_afterpulse_probability",
    "fano_factor_prediction",
    "observed_from_primary",
    "primary_from_observed",
]

AfterpulseModel = Literal["first_order", "cascading"]


def _as_prob(name: str, value: float, strict_upper: bool) -> float:
    p = float(value)
    if not np.isfinite(p):
        raise ValueError(f"{name} must be finite, got {value!r}")
    if p < 0.0:
        raise ValueError(f"{name} must be >= 0, got {p!r}")
    if strict_upper and p >= 1.0:
        raise ValueError(f"{name} must be < 1 for the cascading model, got {p!r}")
    if not strict_upper and p > 1.0:
        raise ValueError(f"{name} must be <= 1, got {p!r}")
    return p


def _check_model(model: str) -> str:
    if model not in ("first_order", "cascading"):
        raise ValueError(f"model must be 'first_order' or 'cascading', got {model!r}")
    return model


def cluster_size_moments(
    afterpulse_probability: float,
    model: AfterpulseModel = "cascading",
) -> dict[str, float]:
    """Moments of the cluster size ``C`` (-). Keys ``mean``, ``second``, ``variance``.

    ``C`` counts the registered events generated by one primary detection,
    including the primary itself, so ``C >= 1`` always.
    """
    _check_model(model)
    if model == "first_order":
        p = _as_prob("afterpulse_probability", afterpulse_probability, strict_upper=False)
        mean = 1.0 + p
        second = 1.0 + 3.0 * p
    else:
        p = _as_prob("afterpulse_probability", afterpulse_probability, strict_upper=True)
        mean = 1.0 / (1.0 - p)
        second = (1.0 + p) / (1.0 - p) ** 2
    return {"mean": mean, "second": second, "variance": second - mean**2}


def observed_from_primary(
    primary_rate_hz: np.ndarray | float,
    afterpulse_probability: float,
    model: AfterpulseModel = "cascading",
) -> np.ndarray:
    """(A1)/(A2) forward: primary registered rate -> observed rate, counts/s."""
    n = np.atleast_1d(np.asarray(primary_rate_hz, dtype=float))
    if np.any(n < 0.0) or not np.all(np.isfinite(n)):
        raise ValueError(f"primary_rate_hz must be finite and >= 0, got {primary_rate_hz!r}")
    return n * cluster_size_moments(afterpulse_probability, model)["mean"]


def primary_from_observed(
    observed_rate_hz: np.ndarray | float,
    afterpulse_probability: float,
    model: AfterpulseModel = "cascading",
) -> np.ndarray:
    """Exact inverse of :func:`observed_from_primary`, counts/s.

    Unique and monotonic in both variants, which is why afterpulsing on its own
    is easy and afterpulsing combined with paralyzable dead time is not.
    """
    m = np.atleast_1d(np.asarray(observed_rate_hz, dtype=float))
    if np.any(m < 0.0) or not np.all(np.isfinite(m)):
        raise ValueError(f"observed_rate_hz must be finite and >= 0, got {observed_rate_hz!r}")
    return m / cluster_size_moments(afterpulse_probability, model)["mean"]


def fano_factor_prediction(
    afterpulse_probability: float,
    model: AfterpulseModel = "cascading",
) -> float:
    """Predicted Fano factor ``Var[N]/E[N]`` of the window count (-).

    ``(1 + 3p)/(1 + p)`` first order, ``(1 + p)/(1 - p)`` cascading. Both equal
    1 at ``p = 0``, as they must.
    """
    mom = cluster_size_moments(afterpulse_probability, model)
    return mom["second"] / mom["mean"]


def effective_afterpulse_probability(
    afterpulse_probability: float,
    dead_time_s: float,
    mean_delay_s: float,
) -> float:
    """(A3) ``p_eff = p exp(-tau / t_ap)`` (-).

    The afterpulse probability actually visible behind a dead time ``tau``,
    assuming exponentially distributed release delays with mean ``t_ap``.
    """
    p = _as_prob("afterpulse_probability", afterpulse_probability, strict_upper=False)
    tau = float(dead_time_s)
    t_ap = float(mean_delay_s)
    if not np.isfinite(tau) or tau < 0.0:
        raise ValueError(f"dead_time_s must be finite and >= 0, got {dead_time_s!r}")
    if not np.isfinite(t_ap) or t_ap <= 0.0:
        raise ValueError(f"mean_delay_s must be finite and > 0, got {mean_delay_s!r}")
    return p * float(np.exp(-tau / t_ap))
