"""Attainable moment set (AMS) geometry.

The attainable moment set of an effector set is the image of the command box
under the effectiveness matrix,

    AMS = { B u : u_min <= u <= u_max }  subset of R^3                    (1)

This is a *zonotope*: the Minkowski sum of ``m`` line segments, one per
effector column. Durham (1994), "Attainable moments for the constrained
control allocation problem", J. Guidance, Control, and Dynamics 17(6),
1371-1373, doi:10.2514/3.21360, is the aerospace statement of the object and
of the fact that its boundary facets are generated by pairs of controls; the
polytope-theoretic facts used below (vertex count, volume) are standard
zonotope results, see Ziegler (1995), "Lectures on Polytopes", Springer GTM
152, Lecture 7.

Two exact constructions are provided:

* ``method="pairwise"`` -- Durham's facet construction. For each pair of
  columns ``(b_i, b_j)`` the candidate facet normal is ``n = b_i x b_j``; every
  effector off that plane is driven to whichever bound maximises
  ``n . b_k u_k``, and the effectors lying *in* the plane sweep out the facet,
  which is itself a 2-D zonotope and is enumerated exactly by an angular walk.
  Taking only the four ``(u_i, u_j)`` corners, as the parallelogram picture
  suggests, loses vertices whenever three or more columns are coplanar --
  which happens as soon as two thruster couples share a plane. Cost is
  ``O(m^2)`` planes and ``O(m log m)`` per plane.
* ``method="bruteforce"`` -- evaluate ``B u`` at all ``2^m`` box vertices.
  Exponential, so it is capped, but it depends on nothing but the definition
  and is therefore the cross-check for the pairwise construction.

Both are passed through ``scipy.spatial.ConvexHull`` to get the true vertex
set, facets and volume.

Known limitation: the pairwise construction decides whether a column lies in a
candidate facet plane with a relative tolerance (1e-9 of the largest entry of
``B``). For a configuration whose columns are within about 1e-8 of parallel or
coplanar, that classification is on a knife edge and the two constructions can
place one vertex differently while agreeing on the volume to 1e-12. Prefer
``method="bruteforce"`` for such geometries when ``m`` allows it.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations

import numpy as np
from numpy.typing import ArrayLike
from scipy.spatial import ConvexHull, QhullError

from .effectors import EffectorSet

__all__ = [
    "AttainableMomentSet",
    "attainable_moment_set",
    "zonotope_volume",
    "expected_vertex_count",
]

_TOL = 1e-12

#: Largest effector count the brute-force construction will attempt
#: (2**18 = 262144 box vertices, a few seconds and ~6 MB).
MAX_BRUTEFORCE_EFFECTORS = 18


@dataclass
class AttainableMomentSet:
    """The attainable moment set of an effector set, as a convex polytope.

    Attributes
    ----------
    vertices
        ``(n_v, 3)`` vertices of the AMS [N*m], in Qhull order.
    hull
        The underlying ``scipy.spatial.ConvexHull``. ``hull.equations`` gives
        the facet half-spaces ``A x + b <= 0``.
    volume
        Enclosed volume [(N*m)^3].
    area
        Surface area [(N*m)^2].
    degenerate
        True when the AMS is flat (rank of the free columns below 3), in which
        case no 3-D hull exists, ``volume`` is 0 and ``vertices`` holds the
        candidate points rather than a hull.
    """

    vertices: np.ndarray
    hull: ConvexHull | None
    volume: float
    area: float
    degenerate: bool
    method: str

    @property
    def n_vertices(self) -> int:
        """Number of distinct vertices."""
        return int(self.vertices.shape[0])

    @property
    def n_facets(self) -> int:
        """Number of hull facets (Qhull simplices; a planar facet of a zonotope
        is generally split into several triangles)."""
        return 0 if self.hull is None else int(self.hull.simplices.shape[0])

    def contains(self, torque: ArrayLike, tol: float = 1e-9) -> np.ndarray:
        """Half-space membership test for one torque or a ``(n, 3)`` batch.

        Uses the hull's facet inequalities directly, so it costs
        ``O(n_facets)`` per query and needs no optimisation. Returns a bool
        scalar for a single torque, a ``(n,)`` array for a batch.

        Raises
        ------
        RuntimeError
            If the AMS is degenerate; a flat set has empty interior and
            membership is not meaningful as a half-space test.
        """
        if self.hull is None:
            raise RuntimeError(
                "AMS is degenerate (rank < 3); use allocation.is_attainable instead"
            )
        tau = np.atleast_2d(np.asarray(torque, dtype=float))
        if tau.shape[1] != 3:
            raise ValueError(f"torque must have last dimension 3, got {tau.shape[1]}")
        eq = self.hull.equations
        inside = np.all(tau @ eq[:, :3].T + eq[:, 3] <= tol, axis=1)
        return inside[0] if np.ndim(torque) == 1 else inside

    def boundary_scale(self, direction: ArrayLike) -> float:
        """Scale ``rho`` at which ``rho * d_hat`` leaves the AMS [N*m].

        This is the "direct allocation" scale of Durham (1993): the magnitude
        at which a torque in the given direction first leaves the attainable
        set. Computed from the facet inequalities, exactly.

        The result is positive whenever the origin lies inside the AMS, which
        holds for any effector set whose command box contains a zero-torque
        point. A stuck-open thruster shifts the AMS off the origin, and then
        this can be negative, meaning the ray in ``direction`` never enters
        the set at a positive scale.
        """
        if self.hull is None:
            raise RuntimeError("AMS is degenerate (rank < 3); boundary_scale is undefined")
        d = np.asarray(direction, dtype=float).reshape(-1)
        if d.shape != (3,):
            raise ValueError(f"direction must have shape (3,), got {np.shape(direction)}")
        norm = float(np.linalg.norm(d))
        if norm < _TOL:
            raise ValueError("direction must be a non-zero vector")
        d = d / norm
        eq = self.hull.equations
        num = -eq[:, 3]
        den = eq[:, :3] @ d
        pos = den > _TOL
        if not np.any(pos):
            return float("inf")
        return float(np.min(num[pos] / den[pos]))


def zonotope_volume(eset: EffectorSet) -> float:
    """Closed-form volume of the attainable moment set [(N*m)^3].

    For a zonotope generated by segments of length ``L_i = upper_i - lower_i``
    along directions ``b_i``, the volume is the sum over all triples of
    generators of the absolute determinant,

        V = sum_{i<j<k} |det(b_i, b_j, b_k)| L_i L_j L_k                  (2)

    Equation (2) is the standard zonotope volume formula (McMullen 1971;
    Shephard 1974; Ziegler 1995, Lecture 7, exercise 7.19). It is independent
    of the hull computation, so ``validate_ams.py`` uses it as the closed-form
    reference against the Qhull volume.

    Cost is ``O(m^3)``; for ``m = 12`` that is 220 determinants.
    """
    b = eset.matrix
    lengths = eset.span
    m = eset.n_effectors
    total = 0.0
    for i, j, k in combinations(range(m), 3):
        det = np.linalg.det(np.column_stack([b[:, i], b[:, j], b[:, k]]))
        total += abs(det) * lengths[i] * lengths[j] * lengths[k]
    return float(total)


def expected_vertex_count(eset: EffectorSet, tol: float = 1e-9) -> int:
    """Vertex count of the AMS for generators in general position.

    A 3-dimensional zonotope with ``g`` non-degenerate generators, no two
    parallel and no three coplanar, has exactly

        n_v = g (g - 1) + 2                                               (3)

    vertices (Ziegler 1995, Lecture 7: a zonotope's face lattice is that of
    the associated hyperplane arrangement, and in R^3 the ``g`` great circles
    cut the sphere into ``g(g-1) + 2`` regions).

    ``g`` here counts distinct generator *lines*: effectors with zero span are
    dropped, and columns that are parallel or antiparallel to one already
    counted are merged, because parallel segments Minkowski-sum into one
    longer segment rather than adding a direction. Three thrusters producing
    +x, -x and +x torque are one generator line, not three.

    Equation (3) still fails when three generator lines are coplanar, and then
    the true count is lower: the orthogonal triad returns 8 from (3) and has 8
    (a cube), but a configuration with a fourth generator lying in the plane
    of two others has fewer than (3) predicts. This function is therefore an
    upper bound in general and an equality in general position;
    ``validate_ams.py`` reports the measured count next to it either way.
    """
    b = eset.matrix[:, eset.free_mask()]
    scale = float(np.max(np.abs(b))) if b.size and np.any(b) else 1.0
    lines: list[np.ndarray] = []
    for i in range(b.shape[1]):
        col = b[:, i]
        n = np.linalg.norm(col)
        if n <= tol * scale:
            continue
        unit = col / n
        if any(np.linalg.norm(np.cross(unit, other)) <= tol for other in lines):
            continue
        lines.append(unit)
    g = len(lines)
    if g < 3:
        return 0
    return g * (g - 1) + 2


def _facet_vertices_2d(
    gens: np.ndarray, lower: np.ndarray, upper: np.ndarray, e1: np.ndarray, e2: np.ndarray
) -> np.ndarray:
    """Exact vertices of the 2-D zonotope generated by in-plane effectors.

    A facet of a 3-D zonotope is itself a zonotope, generated by every column
    that lies in the facet plane. With only two such columns it is the
    parallelogram Durham (1994) describes; with three or more coplanar columns
    -- which happens as soon as two thruster couples share a plane -- it is a
    2p-gon, and taking only the parallelogram corners loses real vertices.

    The 2-D vertices are found by the standard angular walk: order the
    generator half-vectors by direction, start from the extreme point where
    every generator takes its most-negative bound, and add ``2 h_k`` in that
    order, then subtract them, tracing the boundary once.

    Returns ``(n, 3)`` points in the original frame (relative to the plane's
    origin), where ``e1``, ``e2`` are an orthonormal basis of the plane.
    """
    if gens.shape[1] == 0:
        return np.zeros((1, 3))
    coords = np.column_stack([gens.T @ e1, gens.T @ e2])  # (p, 2)
    center2 = 0.5 * (lower + upper) @ coords
    halves = (0.5 * (upper - lower))[:, None] * coords
    norms = np.linalg.norm(halves, axis=1)
    scale = float(np.max(norms)) if norms.size else 0.0
    keep = norms > 1e-12 * max(scale, 1.0)
    halves = halves[keep]
    if halves.shape[0] == 0:
        return (center2[0] * e1 + center2[1] * e2)[None, :]
    flip = (halves[:, 1] < 0.0) | ((halves[:, 1] == 0.0) & (halves[:, 0] < 0.0))
    halves[flip] *= -1.0
    order = np.argsort(np.arctan2(halves[:, 1], halves[:, 0]), kind="stable")
    halves = halves[order]
    v = center2 - halves.sum(axis=0)
    pts2 = [v.copy()]
    for h in halves:
        v = v + 2.0 * h
        pts2.append(v.copy())
    for h in halves[:-1]:
        v = v - 2.0 * h
        pts2.append(v.copy())
    arr = np.asarray(pts2)
    return arr[:, 0, None] * e1[None, :] + arr[:, 1, None] * e2[None, :]


def _plane_basis(normal: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Orthonormal basis of the plane through the origin with the given normal."""
    seed = np.array([1.0, 0.0, 0.0])
    if abs(normal @ seed) > 0.9:
        seed = np.array([0.0, 1.0, 0.0])
    e1 = seed - (seed @ normal) * normal
    e1 /= np.linalg.norm(e1)
    e2 = np.cross(normal, e1)
    return e1, e2


def _pairwise_candidates(eset: EffectorSet) -> np.ndarray:
    """Durham's pairwise facet construction: candidate boundary points."""
    b = eset.matrix
    lo, hi = eset.lower, eset.upper
    m = eset.n_effectors
    scale = float(np.max(np.abs(b))) if np.any(b) else 1.0

    # Distinct candidate facet normals, one per plane spanned by two columns.
    normals: list[np.ndarray] = []
    for i, j in combinations(range(m), 2):
        n = np.cross(b[:, i], b[:, j])
        nn = float(np.linalg.norm(n))
        if nn <= _TOL * scale * scale:
            continue  # parallel columns span no plane
        n = n / nn
        k = int(np.argmax(np.abs(n)))
        if n[k] < 0.0:
            n = -n
        if any(float(np.linalg.norm(n - other)) <= 1e-9 for other in normals):
            continue
        normals.append(n)

    if not normals:
        # Fewer than two independent columns: the set is a segment or a point.
        return np.asarray([b @ lo, b @ hi], dtype=float)

    plane_tol = 1e-9 * scale
    pts: list[np.ndarray] = []
    for n in normals:
        proj = n @ b  # (m,) sensitivity of n . tau to each command
        inplane = np.abs(proj) <= plane_tol
        off = ~inplane
        e1, e2 = _plane_basis(n)
        facet = _facet_vertices_2d(b[:, inplane], lo[inplane], hi[inplane], e1, e2)
        for sign in (1.0, -1.0):
            chosen = np.where(sign * proj[off] > 0.0, hi[off], lo[off])
            base = b[:, off] @ chosen if np.any(off) else np.zeros(3)
            pts.append(base[None, :] + facet)
    return np.vstack(pts)


def _bruteforce_candidates(eset: EffectorSet) -> np.ndarray:
    m = eset.n_effectors
    if m > MAX_BRUTEFORCE_EFFECTORS:
        raise ValueError(
            f"bruteforce enumeration needs 2**{m} box vertices; the cap is "
            f"2**{MAX_BRUTEFORCE_EFFECTORS}. Use method='pairwise'."
        )
    bits = ((np.arange(1 << m)[:, None] >> np.arange(m)) & 1).astype(float)
    u = eset.lower + bits * eset.span
    return u @ eset.matrix.T


def attainable_moment_set(
    eset: EffectorSet, method: str = "pairwise"
) -> AttainableMomentSet:
    """Compute the attainable moment set of ``eset``.

    Parameters
    ----------
    eset
        The effector set. Failed effectors (``lower == upper``) contribute a
        fixed offset, which correctly shifts the AMS rather than shrinking it
        about the origin.
    method
        ``"pairwise"`` (default, ``O(m^2)`` candidates, Durham 1994) or
        ``"bruteforce"`` (all ``2^m`` box vertices, capped at
        ``MAX_BRUTEFORCE_EFFECTORS``).

    Returns
    -------
    AttainableMomentSet
        With ``degenerate=True`` and ``volume=0.0`` when the free columns of
        ``B`` do not span R^3, which is exactly the situation after enough
        effector failures.
    """
    if method == "pairwise":
        pts = _pairwise_candidates(eset)
    elif method == "bruteforce":
        pts = _bruteforce_candidates(eset)
    else:
        raise ValueError(f"unknown method {method!r}; expected 'pairwise' or 'bruteforce'")

    if eset.rank < 3:
        uniq = np.unique(np.round(pts, 12), axis=0)
        return AttainableMomentSet(uniq, None, 0.0, 0.0, True, method)

    try:
        hull = ConvexHull(pts)
    except QhullError:  # pragma: no cover - defensive: rank>=3 should not fail
        uniq = np.unique(np.round(pts, 12), axis=0)
        return AttainableMomentSet(uniq, None, 0.0, 0.0, True, method)
    return AttainableMomentSet(
        vertices=pts[hull.vertices],
        hull=hull,
        volume=float(hull.volume),
        area=float(hull.area),
        degenerate=False,
        method=method,
    )
