"""Kolmogorov / von Karman phase screens and frozen-flow atmospheres.

The screens are generated by the standard Fourier (spectral) method: draw
complex Gaussian coefficients whose variance follows the phase PSD, then
inverse-transform.  Source of the method: B. L. McGlamery, "Computer
simulation studies of compensation of turbulence degraded images", *Proc.
SPIE* **74**, 225-233 (1976); see also Hardy (1998) Sec. 3.6 and
Schmidt, *Numerical Simulation of Optical Wave Propagation* (SPIE Press,
2010), Ch. 9.

Known limitation of the method, quantified in ``validation/``: a discrete
Fourier grid has no power below ``1 / (N * d)``, so the low-order (large-``r``)
part of the structure function is systematically **under-represented**.  The
optional subharmonic augmentation of R. G. Lane, A. Glindemann and J. C.
Dainty, "Simulation of a Kolmogorov phase screen", *Waves in Random Media*
**2**, 209-224 (1992), adds three-by-three low-frequency grids at ``df/3^p``
and recovers most of it.

Frozen flow follows Taylor's hypothesis (G. I. Taylor, *Proc. R. Soc. Lond. A*
**164**, 476-490, 1938): the screen is translated rigidly at the wind speed
and is not otherwise evolved.  This is exact for the temporal statistics only
over times short compared with the eddy turnover time.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .pupil import PupilGrid, piston_removed
from .statistics import KOLMOGOROV_PSD_CYCLIC

__all__ = [
    "FrozenFlowAtmosphere",
    "band_limited_structure_function",
    "phase_screen",
    "screen_psd",
    "structure_function",
]


def screen_psd(
    fx: np.ndarray,
    fy: np.ndarray,
    r0_m: float,
    outer_scale_m: float | None = None,
) -> np.ndarray:
    """Phase PSD sampled on a cyclic-frequency grid [rad^2 m^2].

    Kolmogorov (``outer_scale_m is None``)::

        Phi(f) = 0.022903 r0^(-5/3) f^(-11/3)

    von Karman (finite outer scale ``L0``)::

        Phi(f) = 0.022903 r0^(-5/3) (f^2 + 1/L0^2)^(-11/6)

    Source: Roddier 1981 Eq. 3.14 (Kolmogorov) and Andrews & Phillips 2005,
    *Laser Beam Propagation through Random Media*, 2nd ed., SPIE Press,
    Sec. 3.3 (von Karman).  The ``f = 0`` bin is set to zero: it is pure piston
    and diverges for Kolmogorov.

    Units: ``fx``, ``fy`` in cycles/m; result in rad^2 m^2.
    """
    if not np.isfinite(r0_m) or r0_m <= 0.0:
        raise ValueError(f"r0_m must be finite and > 0, got {r0_m!r}")
    f2 = np.atleast_1d(np.asarray(fx, dtype=float)) ** 2 + np.atleast_1d(
        np.asarray(fy, dtype=float)
    ) ** 2
    const = KOLMOGOROV_PSD_CYCLIC * r0_m ** (-5.0 / 3.0)
    if outer_scale_m is None:
        with np.errstate(divide="ignore", invalid="ignore"):
            psd = const * f2 ** (-11.0 / 6.0)
        return np.where(f2 == 0.0, 0.0, psd)
    if not np.isfinite(outer_scale_m) or outer_scale_m <= 0.0:
        raise ValueError(f"outer_scale_m must be finite and > 0 or None, got {outer_scale_m!r}")
    return const * (f2 + outer_scale_m**-2) ** (-11.0 / 6.0)


def phase_screen(
    n_pix: int,
    pixel_scale_m: float,
    r0_m: float,
    *,
    outer_scale_m: float | None = None,
    n_subharmonics: int = 0,
    rng: np.random.Generator | int | None = None,
    remove_piston: bool = True,
) -> np.ndarray:
    """Generate one square Kolmogorov / von Karman phase screen [rad].

    Parameters
    ----------
    n_pix:
        Screen size in samples per side, ``>= 4``.
    pixel_scale_m:
        Sample spacing ``d`` [m], ``> 0``.
    r0_m:
        Fried parameter [m] at the wavelength the phase refers to, ``> 0``.
    outer_scale_m:
        von Karman outer scale ``L0`` [m], or ``None`` for pure Kolmogorov.
    n_subharmonics:
        Number of Lane et al. (1992) subharmonic levels, ``>= 0``.  Each level
        adds eight coefficients at ``df / 3^p``.  Three levels is the usual
        choice.
    rng:
        ``numpy.random.Generator``, integer seed, or ``None``.
    remove_piston:
        Subtract the screen mean (default; piston is unobservable).

    Returns
    -------
    numpy.ndarray
        ``(n_pix, n_pix)`` phase in radians.

    Notes
    -----
    The screen is **periodic** with period ``n_pix * d`` in both axes — an
    unavoidable property of the Fourier method that frozen-flow simulations
    inherit as a repeat period.
    """
    if int(n_pix) != n_pix or n_pix < 4:
        raise ValueError(f"n_pix must be an integer >= 4, got {n_pix!r}")
    if not np.isfinite(pixel_scale_m) or pixel_scale_m <= 0.0:
        raise ValueError(f"pixel_scale_m must be finite and > 0, got {pixel_scale_m!r}")
    if int(n_subharmonics) != n_subharmonics or n_subharmonics < 0:
        raise ValueError(f"n_subharmonics must be a non-negative integer, got {n_subharmonics!r}")
    n_pix = int(n_pix)
    generator = rng if isinstance(rng, np.random.Generator) else np.random.default_rng(rng)

    df = 1.0 / (n_pix * pixel_scale_m)  # frequency spacing [cycles/m]
    f_axis = np.fft.fftfreq(n_pix, d=pixel_scale_m)
    fx, fy = np.meshgrid(f_axis, f_axis, indexing="xy")
    psd = screen_psd(fx, fy, r0_m, outer_scale_m)

    # Var(Re sum_f c_f e^{2 pi i f.x}) = sum_f sigma_f^2, and we want that to
    # equal sum_f Phi(f) df^2, so sigma_f = sqrt(Phi(f)) * df with
    # c_f = (a + i b) sigma_f, a, b ~ N(0, 1).
    sigma = np.sqrt(psd) * df
    noise = generator.standard_normal((n_pix, n_pix)) + 1j * generator.standard_normal(
        (n_pix, n_pix)
    )
    screen = np.real(np.fft.ifft2(noise * sigma) * n_pix**2)

    if n_subharmonics > 0:
        x = np.arange(n_pix) * pixel_scale_m
        low = np.zeros((n_pix, n_pix), dtype=float)
        for level in range(1, int(n_subharmonics) + 1):
            df_p = df / 3.0**level
            for i in (-1, 0, 1):
                for j in (-1, 0, 1):
                    if i == 0 and j == 0:
                        continue
                    fxs, fys = i * df_p, j * df_p
                    amp = (
                        np.sqrt(
                            float(screen_psd(np.array(fxs), np.array(fys), r0_m, outer_scale_m)[0])
                        )
                        * df_p
                    )
                    c = (generator.standard_normal() + 1j * generator.standard_normal()) * amp
                    # separable phase ramp: exp(2 pi i (fx x + fy y)) = ex outer ey
                    ex = np.exp(2j * np.pi * fxs * x)
                    ey = np.exp(2j * np.pi * fys * x)
                    low += np.real(c * np.outer(ey, ex))
        screen = screen + low

    return screen - screen.mean() if remove_piston else screen


def structure_function(
    screen: np.ndarray,
    max_lag: int | None = None,
    axis: int = 1,
) -> tuple[np.ndarray, np.ndarray]:
    """Empirical phase structure function along one axis of a screen.

    ``D(r) = < [phi(x + r) - phi(x)]^2 >`` estimated over all valid sample
    pairs (no periodic wraparound is used, so the estimate is unbiased by the
    screen's periodicity).

    Returns
    -------
    (lags, d_phi):
        ``lags`` in samples (``1 .. max_lag``), ``d_phi`` in rad^2.
    """
    screen = np.asarray(screen, dtype=float)
    if screen.ndim != 2:
        raise ValueError(f"screen must be 2-D, got shape {screen.shape}")
    if axis not in (0, 1):
        raise ValueError(f"axis must be 0 or 1, got {axis!r}")
    n = screen.shape[axis]
    max_lag = n // 2 if max_lag is None else int(max_lag)
    if max_lag < 1 or max_lag >= n:
        raise ValueError(f"max_lag must lie in [1, {n - 1}], got {max_lag!r}")
    lags = np.arange(1, max_lag + 1)
    out = np.empty(max_lag, dtype=float)
    for k, lag in enumerate(lags):
        if axis == 1:
            diff = screen[:, lag:] - screen[:, :-lag]
        else:
            diff = screen[lag:, :] - screen[:-lag, :]
        out[k] = float(np.mean(diff**2))
    return lags, out


@dataclass
class FrozenFlowAtmosphere:
    """A single translating phase screen sampled onto a pupil grid.

    Parameters
    ----------
    pupil:
        Sampling grid; the screen uses the same sample spacing.
    r0_m:
        Fried parameter [m] at the simulation wavelength, ``> 0``.
    wind_speed_m_s:
        Transverse wind speed [m/s], ``>= 0``.
    frame_time_s:
        Simulation time step [s], ``> 0``.  The screen shifts by
        ``wind_speed * frame_time / d`` samples per frame.
    screen_pixels:
        Size of the generating screen, ``>= 2 * pupil.n_pix``.  Larger screens
        contain more low-frequency power and repeat less often.
    outer_scale_m, n_subharmonics, seed:
        Passed to :func:`phase_screen`.

    Notes
    -----
    Frames are produced by linear interpolation of the screen at a shifted
    position.  The Fourier part of the screen is exactly periodic, so it may
    wrap; the Lane et al. subharmonic part is **not** periodic, and wrapping it
    would splice two uncorrelated edges together and inject a spurious phase
    step.  When ``n_subharmonics > 0`` the atmosphere therefore refuses to
    produce a frame beyond :attr:`max_frames`; ask for a larger
    ``screen_pixels``, a shorter run, or set ``n_subharmonics = 0`` (accepting
    the low-frequency deficit) instead.
    """

    pupil: PupilGrid
    r0_m: float
    wind_speed_m_s: float = 10.0
    frame_time_s: float = 1.0e-3
    screen_pixels: int = 256
    outer_scale_m: float | None = None
    n_subharmonics: int = 3
    seed: int | None = 0

    def __post_init__(self) -> None:
        if not np.isfinite(self.r0_m) or self.r0_m <= 0.0:
            raise ValueError(f"r0_m must be finite and > 0, got {self.r0_m!r}")
        if not np.isfinite(self.wind_speed_m_s) or self.wind_speed_m_s < 0.0:
            raise ValueError(f"wind_speed_m_s must be finite and >= 0, got {self.wind_speed_m_s!r}")
        if not np.isfinite(self.frame_time_s) or self.frame_time_s <= 0.0:
            raise ValueError(f"frame_time_s must be finite and > 0, got {self.frame_time_s!r}")
        if int(self.screen_pixels) != self.screen_pixels:
            raise ValueError("screen_pixels must be an integer")
        if self.screen_pixels < 2 * self.pupil.n_pix:
            raise ValueError(
                f"screen_pixels ({self.screen_pixels}) must be at least "
                f"2 * pupil.n_pix ({2 * self.pupil.n_pix})"
            )
        self._screen = phase_screen(
            int(self.screen_pixels),
            self.pupil.sample_spacing_m,
            self.r0_m,
            outer_scale_m=self.outer_scale_m,
            n_subharmonics=self.n_subharmonics,
            rng=self.seed,
        )

    @property
    def screen(self) -> np.ndarray:
        """The generating screen [rad]."""
        return self._screen

    @property
    def shift_per_frame_pix(self) -> float:
        """Screen translation per frame [samples]."""
        return self.wind_speed_m_s * self.frame_time_s / self.pupil.sample_spacing_m

    @property
    def repeat_period_frames(self) -> float:
        """Frames after which the frozen-flow sequence repeats (``inf`` if still)."""
        step = self.shift_per_frame_pix
        return float("inf") if step == 0.0 else float(self.screen_pixels / step)

    @property
    def max_frames(self) -> float:
        """Frames available before the sliding window would wrap.

        ``inf`` when the wind is still or when no subharmonics are used (the
        Fourier screen is exactly periodic and wrapping is harmless).
        """
        step = self.shift_per_frame_pix
        if step == 0.0 or self.n_subharmonics == 0:
            return float("inf")
        return float(np.floor((self.screen_pixels - self.pupil.n_pix - 1) / step) + 1)

    def frame(self, index: int) -> np.ndarray:
        """Pupil-plane phase at frame ``index`` [rad], piston removed.

        Values outside the pupil mask are zeroed.
        """
        if int(index) != index or index < 0:
            raise ValueError(f"frame index must be a non-negative integer, got {index!r}")
        if index >= self.max_frames:
            raise ValueError(
                f"frame {index} would wrap the non-periodic subharmonic component "
                f"(max_frames = {self.max_frames:.0f} for screen_pixels="
                f"{self.screen_pixels}); increase screen_pixels, shorten the run, "
                f"or set n_subharmonics=0"
            )
        shift = self.shift_per_frame_pix * int(index)
        n = self.pupil.n_pix
        base = int(np.floor(shift))
        frac = shift - base
        rows = np.arange(n)
        cols_a = (np.arange(n) + base) % self.screen_pixels
        cols_b = (np.arange(n) + base + 1) % self.screen_pixels
        window = (1.0 - frac) * self._screen[np.ix_(rows, cols_a)] + frac * self._screen[
            np.ix_(rows, cols_b)
        ]
        return piston_removed(window, self.pupil.mask)

    def frames(self, n_frames: int) -> np.ndarray:
        """Stack of ``n_frames`` consecutive pupil phases, shape ``(T, n, n)``."""
        if int(n_frames) != n_frames or n_frames < 1:
            raise ValueError(f"n_frames must be an integer >= 1, got {n_frames!r}")
        return np.stack([self.frame(k) for k in range(int(n_frames))])


def band_limited_structure_function(
    n_pix: int,
    pixel_scale_m: float,
    r0_m: float,
    lags: np.ndarray,
    outer_scale_m: float | None = None,
) -> np.ndarray:
    """Exact expected structure function of a Fourier screen on this grid.

    For a screen built from independent Gaussian coefficients on the discrete
    frequency grid,

        E[D(r)] = 2 sum_f Phi(f) df^2 [1 - cos(2 pi f_x r)]

    exactly (no Monte Carlo error).  Comparing a measured structure function
    with *this* isolates implementation error, while comparing this with
    ``6.88 (r/r0)^(5/3)`` isolates the method's band-limitation bias.  The
    subharmonic augmentation is not included, so this is the ``n_subharmonics
    = 0`` prediction.

    Parameters
    ----------
    n_pix, pixel_scale_m, r0_m, outer_scale_m:
        Screen parameters, as for :func:`phase_screen`.
    lags:
        Separations in **samples** along the x axis.

    Returns
    -------
    numpy.ndarray
        ``E[D(r)]`` in rad^2, same shape as ``lags``.
    """
    if int(n_pix) != n_pix or n_pix < 4:
        raise ValueError(f"n_pix must be an integer >= 4, got {n_pix!r}")
    if not np.isfinite(pixel_scale_m) or pixel_scale_m <= 0.0:
        raise ValueError(f"pixel_scale_m must be finite and > 0, got {pixel_scale_m!r}")
    lags = np.atleast_1d(np.asarray(lags, dtype=float))
    if np.any(lags < 0.0):
        raise ValueError("lags must be non-negative")
    n_pix = int(n_pix)
    f_axis = np.fft.fftfreq(n_pix, d=pixel_scale_m)
    fx, fy = np.meshgrid(f_axis, f_axis, indexing="xy")
    psd = screen_psd(fx, fy, r0_m, outer_scale_m)
    df2 = (1.0 / (n_pix * pixel_scale_m)) ** 2
    separations = lags * pixel_scale_m
    weight = psd * df2
    return np.array(
        [2.0 * float(np.sum(weight * (1.0 - np.cos(2.0 * np.pi * fx * r)))) for r in separations]
    )
