"""Subset simulation.

Source: Au, S.-K. and Beck, J. L. (2001), "Estimation of small failure
probabilities in high dimensions by subset simulation", Probabilistic
Engineering Mechanics 16(4):263-277.

Method
------
The rare event ``F = {g <= 0}`` is written as the last member of a nested
sequence ``F_1 ⊃ F_2 ⊃ ... ⊃ F_m = F`` with ``F_j = {g <= b_j}``, so that

    P(F) = P(F_1) * prod_{j=2..m} P(F_j | F_{j-1})

and each conditional probability is engineered to equal a fixed ``p0`` (0.1
here) by choosing ``b_j`` as the ``p0``-quantile of the current level's ``g``
values.  Samples conditional on ``F_{j-1}`` are generated by the modified
Metropolis algorithm of the cited paper: the proposal is applied
component-wise with a one-dimensional Metropolis acceptance against the
standard normal marginal, and the resulting candidate is accepted only if it
lies in ``F_{j-1}``.  The component-wise construction is what keeps the
acceptance rate from collapsing as the dimension grows, which is the paper's
central point.

Assumptions and validity
------------------------
Inputs are independent standard normal (the package works in u-space
throughout).  ``p0`` must lie strictly in ``(0, 1)`` and ``p0 * n_per_level``
must be a whole number of seeds, otherwise the chain bookkeeping does not
close.  The estimator is **not** unbiased for finite ``n_per_level``, and its
samples within a level are positively correlated, so:

- no binomial interval is valid for it;
- the standard error reported here assumes independence within levels and is
  therefore a **lower bound** on the true standard error, i.e. optimistic;
- the honest variance in this package comes from independent replications in
  :mod:`rareverify.benchmark`, and that is the number quoted in the README.

The independence-based coefficient of variation is
``sqrt(sum_j (1 - p_j) / (p_j * n_per_level))``, which is the zero-correlation
specialisation of the cited paper's variance expression.
"""

from __future__ import annotations

import math
import time
from dataclasses import dataclass

import numpy as np

from .estimate import RareEventEstimate
from .limitstates import LimitState

__all__ = ["SubsetLevel", "subset_simulation"]


@dataclass(frozen=True)
class SubsetLevel:
    """One intermediate level of a subset-simulation run.

    Attributes
    ----------
    index
        Level number, starting at 1.
    threshold
        Intermediate limit-state threshold ``b_j`` in ``g`` units.  The final
        level always has threshold 0.
    conditional_probability
        ``P(F_j | F_{j-1})``, equal to ``p0`` for every level but the last.
    acceptance_rate
        Fraction of modified-Metropolis candidates accepted while populating
        this level, dimensionless.  A rate near 0 or 1 means the proposal
        standard deviation is badly scaled.
    """

    index: int
    threshold: float
    conditional_probability: float
    acceptance_rate: float


def subset_simulation(
    limit_state: LimitState,
    n_per_level: int = 2000,
    p0: float = 0.1,
    max_levels: int = 20,
    proposal_std: float = 1.0,
    rng: np.random.Generator | None = None,
) -> RareEventEstimate:
    """Estimate ``P(g(X) <= 0)`` by subset simulation.

    Parameters
    ----------
    limit_state
        Limit state to evaluate.
    n_per_level
        Samples per level, ``>= 10``.  ``p0 * n_per_level`` must be a whole
        number and must divide ``n_per_level``.
    p0
        Target conditional level probability, in ``(0, 1)``.  0.1 is the value
        recommended in Au and Beck (2001).
    max_levels
        Give up after this many levels and raise ``RuntimeError``, rather than
        looping forever on a limit state that never reaches zero.
    proposal_std
        Standard deviation of the component-wise random-walk proposal, in
        standard-normal units.
    rng
        Random generator; a default-seeded one is created if omitted.

    Returns
    -------
    RareEventEstimate
        ``is_binomial`` is False.  ``standard_error_kind`` is
        ``"subset-independence-lower-bound"``.  ``diagnostics`` carries
        ``levels``, ``mean_acceptance_rate`` and ``final_conditional``.

    Raises
    ------
    ValueError
        On invalid ``n_per_level``, ``p0`` or chain arithmetic.
    RuntimeError
        If ``max_levels`` is exhausted without the threshold reaching zero.
    """
    if n_per_level < 10:
        raise ValueError(f"n_per_level must be at least 10, got {n_per_level}")
    p0 = float(p0)
    if not 0.0 < p0 < 1.0:
        raise ValueError(f"p0 must lie strictly in (0, 1), got {p0}")
    if max_levels < 1:
        raise ValueError(f"max_levels must be at least 1, got {max_levels}")
    if proposal_std <= 0.0:
        raise ValueError(f"proposal_std must be positive, got {proposal_std}")
    n_seeds = int(round(p0 * n_per_level))
    if n_seeds < 1 or abs(n_seeds - p0 * n_per_level) > 1e-9:
        raise ValueError(
            f"p0 * n_per_level must be a whole number of seeds, got "
            f"{p0 * n_per_level}"
        )
    if n_per_level % n_seeds != 0:
        raise ValueError(
            f"n_seeds={n_seeds} must divide n_per_level={n_per_level} so that "
            "every chain has the same length"
        )
    chain_length = n_per_level // n_seeds

    generator = np.random.default_rng(0) if rng is None else rng
    d = limit_state.dimension
    start = time.perf_counter()

    x = generator.standard_normal((n_per_level, d))
    g = limit_state.g(x)
    evaluations = n_per_level
    probability = 1.0
    levels: list[SubsetLevel] = []
    accept_rates: list[float] = []

    for level_index in range(1, max_levels + 1):
        order = np.argsort(g, kind="stable")
        threshold = float(g[order[n_seeds - 1]])
        if threshold <= 0.0:
            final_count = int(np.count_nonzero(g <= 0.0))
            final_conditional = final_count / n_per_level
            probability *= final_conditional
            levels.append(
                SubsetLevel(
                    index=level_index,
                    threshold=0.0,
                    conditional_probability=final_conditional,
                    acceptance_rate=accept_rates[-1] if accept_rates else float("nan"),
                )
            )
            break
        probability *= p0
        levels.append(
            SubsetLevel(
                index=level_index,
                threshold=threshold,
                conditional_probability=p0,
                acceptance_rate=float("nan"),
            )
        )
        seed_idx = order[:n_seeds]
        current = x[seed_idx].copy()
        current_g = g[seed_idx].copy()
        chain_x = [current.copy()]
        chain_g = [current_g.copy()]
        accepted = 0
        proposed = 0
        for _ in range(chain_length - 1):
            candidate = current + proposal_std * generator.standard_normal(current.shape)
            # Component-wise Metropolis against the standard normal marginal.
            log_ratio = 0.5 * (current**2 - candidate**2)
            take_component = np.log(generator.random(current.shape)) < log_ratio
            proposal = np.where(take_component, candidate, current)
            proposal_g = limit_state.g(proposal)
            evaluations += n_seeds
            in_domain = proposal_g <= threshold
            accepted += int(np.count_nonzero(in_domain))
            proposed += n_seeds
            current = np.where(in_domain[:, None], proposal, current)
            current_g = np.where(in_domain, proposal_g, current_g)
            chain_x.append(current.copy())
            chain_g.append(current_g.copy())
        x = np.concatenate(chain_x, axis=0)
        g = np.concatenate(chain_g, axis=0)
        rate = accepted / proposed if proposed else float("nan")
        accept_rates.append(rate)
        levels[-1] = SubsetLevel(
            index=level_index,
            threshold=threshold,
            conditional_probability=p0,
            acceptance_rate=rate,
        )
    else:
        raise RuntimeError(
            f"subset simulation did not reach g <= 0 within max_levels={max_levels}; "
            f"last threshold {threshold:.6g}. Increase max_levels or check the "
            "limit state."
        )

    wall = time.perf_counter() - start
    variance_terms = sum(
        (1.0 - level.conditional_probability)
        / (level.conditional_probability * n_per_level)
        for level in levels
        if level.conditional_probability > 0.0
    )
    cov_lower_bound = math.sqrt(variance_terms)
    standard_error = probability * cov_lower_bound
    finite_rates = [r for r in accept_rates if math.isfinite(r)]
    return RareEventEstimate(
        method="subset-simulation",
        estimate=probability,
        standard_error=standard_error,
        n_samples=n_per_level * len(levels),
        true_evaluations=evaluations,
        n_failures=int(np.count_nonzero(g <= 0.0)),
        is_binomial=False,
        effective_sample_size=float("nan"),
        wall_seconds=wall,
        standard_error_kind="subset-independence-lower-bound",
        contributions=np.zeros(0),
        diagnostics={
            "levels": float(len(levels)),
            "final_conditional": levels[-1].conditional_probability,
            "mean_acceptance_rate": (
                float(np.mean(finite_rates)) if finite_rates else float("nan")
            ),
            "cov_independence_lower_bound": cov_lower_bound,
            "chain_length": float(chain_length),
            "n_seeds": float(n_seeds),
        },
    )
